project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: One Utah Data Science Hub
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/UtahDataSciHub
      - icon: envelope
        href: mailto:data-science-hub@utah.edu?subject=Utah%20Data%20Science%20Webpage%20Request
    style: "docked"
    search: true
    logo: images/NewHubLogoSquare.png
    contents:
      - text: "Overview"
        href: about.qmd
      - section: "Funding Opportunities"
        href: funding.qmd
        contents: 
          - text: "NIH Funding"
            href: funding_nih.qmd
          - text: "NSF Funding"
            href: funding_nsf.qmd
          - text: "Other Funding"
            href: funding_other.qmd
          - text: "Archived Funding"
            href: funding_archived.qmd
      - section: "Education"
        href: education.qmd
        contents:
          - text: "Data Science Series"
            href: education_courses.qmd
          - text: "Educational Workshops"
            href: education_workshops.qmd
          - text: "Degree-based Programs"
            href: education_degrees.qmd
          - text: "Archived Courses"
            href: education_archived.qmd
      - text: "Events and Seminars"
        href: events.qmd
      - text: "Data Science Roster"
        href: roster.qmd
      - text: "Positions and Projects"
        href: projects.qmd
      - text: "Strengths and Aspirations"
        href: research.qmd
      - text: "News and Highlights"
        href: news.qmd
      - text: "Data Resources"
        href: data.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.utah-data-science-hub\.github\.io\/**'
    toc: true
    
editor: source

