project:
  type: website
  output-dir: docs
  

website:
  title: One Utah Data Science Hub
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/UtahDataSciHub
      - icon: envelope
        href: mailto:penny.atkins@hsc.utah.edu?subject=Utah%20Data%20Science%20Page%20Request
    style: "docked"
    search: true
    logo: images/HubLogo.png
    contents:
      - text: "Overview"
        href: about.qmd
      - section: "Funding Opportunities"
        contents: 
          - text: "NIH Funding"
            href: funding_nih.qmd
          - text: "NSF Funding"
            href: funding_nsf.qmd
          - text: "Other Funding"
            href: funding_other.qmd
          - text: "Archived Funding"
            href: funding_archived.qmd
      - section: "Education"
        contents:
          - text: "Current Opportunities"
            href: education_courses.qmd
          - text: "Degree-based Programs"
            href: education_degrees.qmd
          - text: "Other Resources"
            href: education_resources.qmd
          - text: "Archived Courses"
            href: education_archived.qmd
      - text: "Events and Seminars"
        href: events.qmd
      - text: "News and Highlights"
        href: news.qmd
      - section: "WIP - Coming Soon!"
        contents:
          - text: "Data Resources"
            href: data.qmd
          - text: "Roster"
            href: roster.qmd
          - text: "Research Areas"
            href: research.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.utah-data-science-hub\.github\.io\/**'
    toc: true
    
editor: source

