project:
  type: website
  output-dir: docs

website:
  title: "One Utah Data Science Hub"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "General"
        contents: 
        - about.qmd
        - events.qmd
        - data.qmd
      - section: "Funding Opportunities"
        contents: 
          - funding_nih.qmd
          - funding_nsf.qmd
          - funding_other.qmd
          - funding_archived.qmd
      - section: "Education"
        contents:
          - education_courses.qmd
          - education_resources.qmd
          - education_archived.qmd
      - section: "Research Areas"
        contents:
          - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

