---
title: "Degree-based Programs"
format: html
---

## Undergraduate Education

### Degrees

-   [BS in Data Science](https://www.cs.utah.edu/undergraduate/academic-programs/undergraduate-academic-program-overview/data-science/#data-science){target="_blank"} from the Kahlert School of Computing
-   [BS in Information Systems](https://eccles.utah.edu/programs/undergraduate/academics/majors/information-systems/){target="_blank"} from the David Eccles School of Business
-   [BS in Finance with Fintech Emphasis](https://eccles.utah.edu/programs/undergraduate/academics/majors/finance/){target="_blank"} from the David Eccles School of Business

### Certificates

-   [Undergraduate Certificates in Data Science](https://www.cs.utah.edu/wp-content/uploads/2022/08/DS_Requirement-Sheet-01.21.22.pdf){target="_blank"} from the Kahlert School of Computing
-   [Undergraduate Certificate in Data Fluency](https://www.cs.utah.edu/wp-content/uploads/2022/08/DF_Requirement-Sheet-01.21.22.pdf){target="_blank"} from the Kahlert School of Computing

## Graduate Education

### Degrees

-   College of Engineering
    -   MS, ME, or PhD in Biomedical Engineering, [Data Science and Computation Track](https://www.bme.utah.edu/graduate-program-overview/track-in-data-science-and-computation/){target="_blank"}
    -   MS or PhD in [Computing](https://www.cs.utah.edu/graduate/academic-programs/ms-and-phd-programs/){target="_blank"} from the Kahlert School of Computing, [Data Science Option within Data Management & Analysis Track](https://docs.google.com/document/d/1rFmp-gvDoA4YvUAph2r_dXbQqJxV7HH5KlEA9OfRNEk/edit) or [Artificial Intelligence Track](https://docs.google.com/document/d/1rFmp-gvDoA4YvUAph2r_dXbQqJxV7HH5KlEA9OfRNEk/edit){target="_blank"}
-   School of Medicine
    -   [MS in Biomedical Informatics](https://medicine.utah.edu/dbmi/academics-education/masters){target="_blank"}, [Data Science Track](https://medicine.utah.edu/dbmi/academics-education/masters/track-data-science){target="_blank"}
    -   [PhD in Biomedical Informatics](https://medicine.utah.edu/dbmi/academics-education/phd-program){target="_blank"}, [Data Science, Analytics, AI, and Computational Methods Track](https://medicine.utah.edu/dbmi/academics-education/phd-program/data-analytics-decision-support){target="_blank"}
    -   [PhD in Population Health Sciences](https://medicine.utah.edu/population-health-sciences/phd/emphases){target="_blank"}, Biostatistics Track
-   David Eccles School of Business
    -   [MS in Business Analytics](https://eccles.utah.edu/programs/master-of-science-in-business-analytics/){target="_blank"}
    -   [MS in Cybersecurity Management](https://eccles.utah.edu/programs/master-of-science-in-cybersecurity-management/){target="_blank"}
    -   [MS in Information Systems](https://eccles.utah.edu/programs/master-of-science-in-information-systems/){target="_blank"}
    -   [MS in Information Systems, Online](https://eccles.utah.edu/programs/master-of-science-in-information-systems-online/){target="\_blank"}
    -   [PhD in Business Administration](https://eccles.utah.edu/programs/phd-in-business-administration/), [Information Systems Track](https://eccles.utah.edu/programs/phd-in-business-administration/academic-tracks/information-systems/){target="_blank"}
-   The Graduate School
    -   [Masters of Statistics](https://mstat.utah.edu/){target="_blank"}, [Mathematics Track](https://mstat.utah.edu/degree-options/mathematics.php){target="_blank"}
    -   [Professional Masters in Science and Technology](https://pmst.utah.edu/){target="_blank"}, [Computational and Data Science Track](https://pmst.utah.edu/computational-and-data-science-program-of-study/){target="_blank"}

### Certificates

-   Kahlert School of Computing
    -   [Certificate in Data Science](https://www.cs.utah.edu/graduate/academic-programs/certificate-programs/graduate-certificate-in-data-science/){target="_blank"}
    -   [Certificate in Deep Learning](https://www.cs.utah.edu/graduate/academic-programs/certificate-programs/graduate-certificate-in-deep-learning/){target="_blank"}
    -   [Certificate in Secure Computing](https://online.utah.edu/certificates/secure-computing-certificate/index.php){target="_blank"}
-   David Eccles School of Business
    -   [Certificate in Business Analytics](https://eccles.utah.edu/programs/master-of-science-in-information-systems/graduate-certificate/){target="_blank"}
    -   [Certificate in Cybersecurity Management](https://eccles.utah.edu/programs/master-of-science-in-information-systems/graduate-certificate/){target="_blank"}
    -   [Certificate in Information Systems](https://eccles.utah.edu/programs/master-of-science-in-information-systems/graduate-certificate/){target="_blank"}
-   Biomedical Informatics within the School of Medicine
    -   [Informatics Certificate](https://medicine.utah.edu/dbmi/academics-education/other/graduate-certificate){target="_blank"}

## Professional Education

-   [AI Boot Camp](https://bootcamps.continue.utah.edu/artificial-intelligence/){target="_blank"}
-   [Data Analytics Boot Camp](https://bootcamps.continue.utah.edu/data/){target="_blank"}
-   [Cybersecurity Boot Camp](https://bootcamps.continue.utah.edu/cybersecurity/){target="_blank"}
-   [Machine Learning and AI MicroBootCamp](https://bootcamps.continue.utah.edu/micro/artificial-intelligence/landing/){target="_blank"}
