---
title: "Educational Opportunities"
format: html
---

## Software Carpentries
Software Carpentries workshops are offered in person over two-days, including breakfast, lunch, and snacks. Topics covered will depend on the specific workshop, but could include R, python, SQL, Unix, and more.  

### Introduction to R
**When:** August 21-22 2023\
**Where:** HSEB, Salt Lake City, UT 84113\
**Instructors:** Rebecca Barter, George Vega Yon\
[Register to save your spot!](https://docs.google.com/forms/d/e/1FAIpQLSf3XyQ345D6nm-AKd4srWDGQ7C0UxDZczuyrOGttz66gFIgoQ/viewform)
Additional Information can be found on the [website](https://uofudelphi.github.io/2023-08-21-Intro_R/). 

## Data Science Series
Each course will run for four weeks with an asynchronous lecture, virtual office hour session, and project based assignments each week and will be taught in either R or Python. The series has been designed by Dr. Rebecca Barter and will include the following modules: introduction, data cleaning, data visualization, and modeling. \
  
### Introduction to R
**When:** August/September 2023\
**Where:** Virtual\
**Instructor:** Rebecca Barter

### Data Cleaning in R
**When:** June 12 - July 7, 2023 (*Pilot*)\
**Where:** Virtual\
**Instructor:** Rebecca Barter  
Additional Information can be found on the [website](https://utah.instructure.com/courses/907377).

**When:** September/October 2023\
**Where:** Virtual\
**Instructor:** Rebecca Barter

### Data Visualization in R
**When:** October/November 2023\
**Where:** Virtual\
**Instructor:** Rebecca Barter

### Modeling in R
**When:** November/December 2023\
**Where:** Virtual\
**Instructor:** Rebecca Barter
