---
title: "Archived Education"
format: html
---

## Software Carpentries
### Introduction to Data Analysis in Python
**When:** February 8-9, 2024, 9am-5pm\
**Where:** [HELIX](https://maps.app.goo.gl/3w96QNsCt9ASd3d77){target="_blank"} GS155 (Alder)\
**Instructors:** Rebecca Barter, Alec Chapman\
Contact [Penny Atkins](mailto:penny.atkins@hsc.utah.edu) with any inquiries. [Register to save your spot!](https://forms.gle/wGrVndw1pbrzb9fX9){target="_blank"}
Additional information can be found on the [website](https://uofudelphi.github.io/2024-02-08-python/){target="_blank"}.

### Databases and SQL
**When:** December 1, 2023\
**Where:** HSEB 1730, Salt Lake City, UT 84113\
**Instructors:** Rebecca Barter, Alec Chapman\
[Register to save your spot!](https://forms.gle/WC5Q9NsV52LaKjuA8){target="_blank"}
Additional information can be found on the [website](https://uofudelphi.github.io/2023-12-01-sql/){target="_blank"}.

### Version Control and Collaboration with Git and GitHub
**When:** November 30, 2023\
**Where:** HSEB 1730, Salt Lake City, UT 84113\
**Instructors:** Rebecca Barter, George Vega Yon\
[Register to save your spot!](https://forms.gle/a6b8NkncHRKes8Pf8){target="_blank"} 
Additional information can be found on the [website](https://uofudelphi.github.io/2023-11-30-git/){target="_blank"}.

### Introduction to Data Analysis with Python
**When:** Tuesdays and Thursdays 9-10am from October 24-November 16  
**Where:** Virtual  
**Instructors:** Rebecca Barter  
[Register to save your spot!](https://forms.gle/3wpYrWQGy7EMrXmK6){target="_blank"} 
Additional information will be shared with registered participants prior to the course.

### Introduction to R
**When:** August 21-22 2023\
**Where:** HSEB, Salt Lake City, UT 84113\
**Instructors:** Rebecca Barter, George Vega Yon\
[Register to save your spot!](https://docs.google.com/forms/d/e/1FAIpQLSf3XyQ345D6nm-AKd4srWDGQ7C0UxDZczuyrOGttz66gFIgoQ/viewform)
Additional Information can be found on the [website](https://uofudelphi.github.io/2023-08-21-Intro_R/).

### Introduction to R
**When:** May 17-18, 2023\
**Where:** EHSEB 2680, 26 2000 E, Salt Lake City, UT 84113\
**Instructors:** Rebecca Barter, George Vega Yon\
Additional Information can be found on the [website](https://uofudelphi.github.io/2023-05-17-Intro_R/).

### Introduction to Python
**When:** October 11-12, 2022\
**Where:** EHSEB 3515B, 26 2000 E, Salt Lake City, UT 84112\
**Instructors:** Janani Hariharan, Harriet Dashnow\
Additional Information can be found on the [website](https://quinlan-lab.github.io/2022-10-11-Utah-Python/).



## Data Science Modules

### Data Cleaning in R
**When:** June 12 - July 7, 2023 (*Pilot*)\
**Where:** Virtual\
**Instructor:** Rebecca Barter  
Additional Information can be found on the [website](https://utah.instructure.com/courses/907377).