---
title: "Seminars and Events"
format: html
---

Check out our calendar of upcoming events and seminars in our [Google Calendar](https://calendar.google.com/calendar/u/0?cid=Y2Y0ZDA4OThhMjJiMmQxOTY5NzU1ZDRiYmU3NzA2M2U4MGVhNDgxMGEyNGEyYTI0ZWQ4NDAwM2IyMjU0NGY1NEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) of upcoming events and seminars.

<iframe src="https://calendar.google.com/calendar/embed?src=cf4d0898a22b2d1969755d4bbe77063e80ea4810a24a2a24ed84003b22544f54%40group.calendar.google.com&amp;ctz=America%2FDenver" style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
</iframe>


## Fall 2023 Networking Event
**Date:** September 12, 2023  
**Time:** 5pm - 7pm  
**Location:** Thomas S. Monson Center  
We invite faculty and staff to present their research highlights, research needs, and burning questions related to data science in a lightning-talk format. 

<object data="images/SaveTheDate_Networking2023.pdf" type="application/pdf" width="800" height="450" style="overflow:hidden" scrolling="no">
</object>

## DELPHI Symposium  
**Date:** October 20, 2023  
**Time:** 8:30am - 4:00pm  
**Location:** Cleone Peterson Eccles Alumni House  
Register and submit your abstract for a poster or lightning talk [here](https://forms.gle/FuUCPC7J8BXetwEeA). 

<object data="images/DELPHISymposium_SaveTheDate.pdf" type="application/pdf" width="800" height="445" style="overflow:hidden" scrolling="no">
</object>

## DATASET Discovery Workshops
### Multidisciplinary Data Integration for Climate Resilience in the American West
**Hosted by:** PI: Tabitha Benney; Co-PIs: Divya Chandrasekhar, Masood Parvania, John Horel, Manish Parashar  
**Date:** October 19-20, 2023  
**Location:** West Ballroom of the Union  
Additional details forthcoming!
<!--  + Keynote: What is the current and future role of data science in building climate change resilience and advancing adaptative capacity in the western U.S.?
  + Track 1: Critical Infrastructure Systems Data, Masood Parvania and Heather Holmes
  + Track 2: Utilizing Environmental Data, John Horel
  + Track 3: Social and Health Equity and Data Science, Tabitha Benney and Cheryl Pirozzi
  + Track 4: Data Diversity and Challenges of Integration, Manish Parashar and Divya Chandrasekhar -->
  
### Bias, Ethics, and Trustworthiness in Data Science and AI
This is an in-person, mixer event that explores the challenges and opportunities of data science and AI in the modern world. 

Join us over lunch for a mixer event that will include **lightning talks, poster presentations, and engaging networking opportunities** with researchers across campus who are delving into the ethical considerations of data science and AI. Together, we will highlight the importance of conducting trustworthy research and identify ways to mitigate bias in our data and analyses. We look forward to seeing you!

**Date:** September 15, 2023  
**Time:** 11AM - 2PM  
**Location:** Henriksen Conference Room, Cleone Peterson Eccles Alumni House.  

If you are interested in attending the mixer event, please [register here](https://www.eventbrite.com/e/bias-ethics-and-trustworthiness-in-data-science-and-ai-tickets-666914688787).

If you would like to share your research as a presenter of a 4-minute lightning talk speaker or poster at the event, please [submit a brief abstract using this form](https://forms.gle/SgapNEdxRz1cpzJ8A) by July 15. Note that submitting an abstract will automatically register you for the event.

We also encourage you to help us spread the word by sharing this invitation with your colleagues across campus.

This event is supported by the Data Science and Ethics of Technology (DATASET) Initiative. If you have any questions, please reach out to [Rebecca Barter](mailto:rebecca.barter@hsc.utah.edu).


<object data="images/bias_event.pdf" type="application/pdf" width="800" height="1100" style="overflow:hidden" scrolling="no">
</object>
  
## Other Seminars on Campus
* [Utah Center for Data Science](https://datascience.utah.edu/seminar.html)  
* [Scientific Computing and Imaging Institute](https://www.sci.utah.edu/the-institute/events.html)
* [Human Genetics](https://www.genetics.utah.edu/events)
