---
title: "NSF Funding Opportunities"
format: html
---
<!-- ### [](){target="_blank"}
* S
* Deadline: 
* Award: $ for durations up to  years -->
## Proposals Accepted Anytime
### [Research Infrastructure in the Social and Behavioral Sciences (RISBS)](https://new.nsf.gov/funding/opportunities/research-infrastructure-social-behavioral-sciences){target="_blank"}
* Supports projects that create computational tools and data to facilitate basic research in the social and behavioral sciences that can lead to improved health, prosperity and security. The RISBS program administers separate solicitations for the American National Election Study (ANES), the General Social Survey (GSS) and the Panel Study of Income Dynamics (PSID).

### [Computer and Information Science and Engineering: Core Programs](https://new.nsf.gov/funding/opportunities/computer-information-science-engineering-core){target="_blank"}
* Supports research and education projects that develop new knowledge in all aspects of computing, communications, and information science and engineering, as well as advanced cyberinfrastructure, through the following core programs:
  + Division of Computing and Communication Foundations (CCF): Algorithmic Foundations (AF) program; Communications and Information Foundations (CIF) program; Foundations of Emerging Technologies (FET) program; and Software and Hardware Foundations (SHF) program.
  +Division of Computer and Network Systems (CNS): Computer Systems Research (CSR) program; and Networking Technology and Systems (NeTS) program.
  + Division of Information and Intelligent Systems (IIS): Human-Centered Computing (HCC) program; Information Integration and Informatics (III) program; and Robust Intelligence (RI) program.
  + Office of Advanced Cyberinfrastructure (OAC): OAC Core Research (OAC Core) program.
* Awards:
  + *Small Projects* $600K for durations up to three years (CCF, CNS, and IIS only)
  + *Medium Projects* $1.2M for durations up to four years (CCF, CNS, and IIS only)
  + *OAC Core Projects* $600K for durations up to three years (OAC only)

### [Infrastructure Innovation for Biological Research (Innovation)](https://new.nsf.gov/funding/opportunities/infrastructure-innovation-biological-research){target="_blank"}
* Supports research to design or improve research tools and methods with a focus on research infrastructure in three program areas: bioinformatics, instrumentation and research methods.
* Award: The size and duration of any individual request should be justified by the amount and complexity of the work to be accomplished (up to approximately $500K-1M).

### [Rapidly Accelerating Research on Artificial Intelligence in K-12 Education in Formal and Informal Settings](https://www.nsf.gov/pubs/2023/nsf23097/nsf23097.jsp){target="_blank"}
* Supports time-sensitive research including the development of AI tools and environments to advance age-appropriate equitable learning and inclusive teaching, support of learning about and interest in AI, use of AI to teach AI; and the integration of generative AI in education in an ethical, responsible, and effective way.
* Award: $200K for durations up to one year

### [Energy, Power, Control, and Networks (EPCN)](https://new.nsf.gov/funding/opportunities/energy-power-control-networks-epcn-0){target="_blank"}
* Supports research in modeling, optimization, learning, adaptation and control of networked multi-agent systems; higher-level decision making; and dynamic resource allocation and risk management.
* Award: The size and duration of any individual request should be justified by the amount and complexity of the work to be accomplished.

### [Secure and Trustworthy Cyberspace (SaTC)](https://new.nsf.gov/funding/opportunities/secure-trustworthy-cyberspace-satc){target="_blank"}
* Supports research addressing cybersecurity and privacy, drawing on expertise in one or more of these areas: computing, communication and information sciences; engineering; economics; education; mathematics; statistics; and social and behavioral sciences.
* Awards: 
  + *CORE and Transition to Practice (TTP) Small Projects* $600K for durations up to three years
  + *CORE and TTP Medium Projects* $1.2M for durations up to four years
  + *EDU Projects* $400K for durations up to three years or $500K for durations up to three years for collaborations between a cybersecurity subject matter expert and an education researcher
  
### [Computational and Data-Enabled Science and Engineering (CDS&E)](https://new.nsf.gov/funding/opportunities/computational-data-enabled-science-engineering-2){target="_blank"}
* Supports research that uses new computational and data science approaches to advance knowledge and accelerate discovery in science and engineering.
* Deadline: Depends on the Division; anytime or annually in the Fall
* Award: The size and duration of any individual request should be justified by the amount and complexity of the work to be accomplished. 

### [Condensed Matter and Materials Theory (CMMT)](https://new.nsf.gov/funding/opportunities/condensed-matter-materials-theory-cmmt-0){target="_blank"}
* Supports fundamental research and education on hard and soft materials and related phenomena; the development of associated analytical, computational and data-centric techniques; and predictive materials-specific theory, simulation and modeling.
* Deadline: Accepted anytime (recommended to avoid April 15-June 15)
* Award: The size and duration of any individual request should be justified by the amount and complexity of the work to be accomplished.  

### [Cyberinfrastructure for Public Access and Open Science (CI PAOS)](https://new.nsf.gov/funding/opportunities/cyberinfrastructure-public-access-open-science-ci){target="_blank"}
* Supports new and transformative socio-technical partnerships supporting research data infrastructure ecosystems across domains through early-stage collaborative activities between cyberinfrastructure researchers, scientists, research computing experts, data management experts, research labs, university libraries, and other communities of practice. 
* Award: The size and duration of any individual request should be justified by the amount and complexity of the work to be accomplished.



## Upcoming Proposal Deadlines

### [Cyber-Physical Systems (CPS)](https://new.nsf.gov/funding/opportunities/cyber-physical-systems-cps){target="_blank"}
* Supports research on engineered systems with a seamless integration of cyber and physical components, such as computation, control, networking, learning, autonomy, security, privacy and verification, for a range of application domains.
  + *Small Projects* $500K for durations up to three years; rolling deadline ending May 31 annually
  + *Medium Projects* $1M for durations up to three years; rolling deadline ending May 31 annually
  + *Frontier Projects* up to $7M for durations up to five years; deadline September 3, 2024 
* [DCL: Medical / Health Cyber Physical Systems Proposals](https://www.nsf.gov/pubs/2024/nsf24017/nsf24017.jsp){target="_blank"}<!-- November 8, 2023 -->

### [Emerging Frontiers in Research and Innovation (EFRI): Biocomputing through EnGINeering Organoid Intelligence (BEGIN OI)](https://new.nsf.gov/funding/opportunities/emerging-frontiers-research-innovation-efri){target="_blank"}
* Supports foundational and transformative research to advance the design, engineering, and fabrication of organoid systems that are capable of processing information dynamically while interfacing with non-living systems.
  + Research Thread 1: Biocomputing Theory and Modelling
  + Research Thread 2: Biology-Integrated Culture Maintenance and Hardware Systems
  + Research Thread 3: Ethical, Legal, and Social Implications (ELSI)
* Deadline: September 12, 2024 (LOI), December 12, 2024 (Full Proposal)
* Award: $2M for durations up to four years



## Upcoming Recurring Proposal Deadlines
### [Privacy-Preserving Data Sharing in Practice (PDaSP)](https://new.nsf.gov/funding/opportunities/privacy-preserving-data-sharing-practice-pdasp){target="_blank"}
* Track 1: Advancing key technologies to enable practical PPDSA solutions: $500K - $1M for up to 2 years 
* Track 2: Integrated and comprehensive solutions for trustworthy data sharing in application settings: $1M - $1.5M for up to 3 years 
* Track 3: Usable tools, and testbeds for trustworthy sharing of private or otherwise confidential data: $500K - $1.5M for up to 3 years
* Deadline: September 27, 2024

### [Decision, Risk and Management Sciences (DRMS)](https://new.nsf.gov/funding/opportunities/decision-risk-management-sciences-drms-0){target="_blank"}
* Supports research that increases understanding of how individuals, organizations and societies make decisions. Areas include judgment, decision analysis and aids, risk analysis and communication, public policy decision making and management science.
* Deadline: January 18 and August 18; annually

### [A Science of Science Approach to Analyzing and Innovating the Biomedical Research Enterprise (SoS:BIO)](https://new.nsf.gov/funding/opportunities/science-science-approach-analyzing-innovating){target="_blank"}
* Supports the development of theories, models, analytical tools, data and metrics that can inform the science of science, science policy, public outcomes and the advancement of the scientific enterprise, with a focus on the biomedical sciences.
* Deadline: September 9, 2024; recurring annually on February 9 and September 9
* Award: $100K-250K/year (total) for durations up to 4 years

### [Experiential Learning for Emerging and Novel Technologies (ExLENT)](https://new.nsf.gov/funding/opportunities/experiential-learning-emerging-novel-technologies){target="_blank"}
*   Supports inclusive experiential learning opportunities that provide cohorts of diverse learners with the skills needed to succeed in emerging technology fields.
    *   *Pivots* track aims to attract individuals not currently enrolled in post-secondary educational programs, and have acquired useful skills such as time management, communication, and teamwork in non-emerging technology careers.
    *   *Beginnings* track aims to provide individuals possessing some existing STEM competencies (e.g., those with stackable certificates in STEM or those enrolled in associate's degree programs, etc.) with experiential learning opportunities that deepen knowledge and skills in emerging technology fields.
    *   *Explorations* track aims to provide individuals with limited or no specialized STEM education the inspiration and opportunity to explore the potential of a career path in emerging technology fields.
*   Deadline: September 12, 2024; annually thereafter on the second Thursday in September
*   Award: \$1M for durations up to three years

### [Community Infrastructure for Research in Computer and Information Science and Engineering (CIRC)](https://new.nsf.gov/funding/opportunities/cise-community-research-infrastructure-ccri){target="_blank"}
*   *Planning Community Infrastructure (Planning)* awards support planning efforts to engage research communities to develop new CISE community research infrastructures. Such an infrastructure could be eventually funded through the CIRC program (Planning-C) or the [Mid-scale RI-1](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-1-mid-scale-ri-1){target="_blank"} or [Mid-scale RI-2](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-2-mid-scale-ri-2){target="_blank"} programs (Planning-M).
* *Exploratory Development (Dev)* awards support activities that involve the validation of one or more unproven infrastructure designs and/or technologies, which, if validated, could enable transformative community research infrastructure in the future. Successful projects are expected to provide the technical foundations necessary to pursue subsequent CIRC (**New** or **Grand**), [Mid-scale RI-1](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-1-mid-scale-ri-1){target="_blank"}, or [Mid-scale RI-2](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-2-mid-scale-ri-2){target="_blank"} projects.
*   *Medium Community Infrastructure (Medium)* awards support the creation of new CISE community research infrastructure or the enhancement of existing CISE community research infrastructure with integrated tools, resources, user services, and research community outreach to enable innovative CISE research opportunities to advance the frontiers of the CISE core research areas.
*   *Grand Community Infrastructure (Grand)* awards support projects involving significant efforts to develop new CISE community research infrastructure or to enhance and sustain an existing CISE community research infrastructure to enable world-class CISE research opportunities for broad-based communities of CISE researchers that extend well beyond the awardee organization(s).
*   Deadline: September 13, 2024, annually thereafter on the second Friday in September
*   Award: *Planning* \$50-250K for durations up to two years; *Dev* \$250-750K for durations up to two years; *Medium* \$750K-2M for durations up to three years; *Grand* \$2-5M for durations up to five years

### [Engineering Research Center (ERC)](https://new.nsf.gov/funding/opportunities/gen-4-engineering-research-centers-erc){target="_blank"}
*   Convergent Research and Innovation through Inclusive Partnerships and Workforce Development
*   Supports high-risk, high-payoff research centers focused on advancing engineered systems technology and education through multidisciplinary, cross-sector partnerships.
*   Deadline: September 2024 (LOI), October 2024 (Preliminary Proposal), May 2025 (Full Proposal); dates anticipated, recurring every other year
*   Award: \$15M for durations up to seven years

### [Smart Health and Biomedical Research in the Era of Artificial Intelligence and Advanced Data Science (SCH)](https://new.nsf.gov/funding/opportunities/smart-health-biomedical-research-era-artificial){target="_blank"}
* Supports the development of transformative high-risk, high-reward advances in computer and information science, engineering, mathematics, statistics, behavioral and/or cognitive research to address pressing questions in the biomedical and public health communities. 
  + Fairness and Trustworthiness
  + Transformative Analytics in Biomedical and Behavioral Research
  + Next Generation Multimodal and Reconfigurable Sensing Systems
  + Cyber-Physical Systems
  + Robotics
  + Biomedical Image interpretation
  + Unpacking Health Disparities and Health Equity
* Deadline: October 3, 2024; October 3, 2025
* Award: $300K/year (total) for durations up to four years
<!--* [DELPHI and DHI Townhall on Aug 31 at 10:30 am](https://utah.zoom.us/j/93613638947?pwd=MFB0RHRoemR2UUpUcVRXbGVmajY0dz09){target="_blank"}, [NIH/NSF Webinar on Sept 25 at 1pm](https://nsf.zoomgov.com/webinar/register/WN_ctCzc3alRQyXZAX0rS1Fww){target="_blank"}-->

### [Advanced Technological Education (ATE)](https://new.nsf.gov/funding/opportunities/advanced-technological-education-ate){target="_blank"}
* Supports the education of technicians for the high-technology fields that drive our nation's economy. 
  + Track 1: Small scale projects
  + Track 2: Projects
  + Track 3: Consortia for Innovations in Technical Education
  + Track 4: ATE Center with areas of interest defined through October 2028 
* Deadline: October 3, 2024; recurring on the first Thursday in October thereafter
* Award: $475K for three years (Track 1), $1M for three years (Track 2), $1.2-3M for three to four years (Track 3), $7.5M for five years (Track 4)

### [Mathematical Foundations of Artificial Intelligence (MFAI)](https://new.nsf.gov/funding/opportunities/mathematical-foundations-artificial-intelligence){target="_blank"}
* Supports research collaborations consisting of mathematicians, statisticians, computer scientists, engineers, and social and behavioral scientists focused on the mathematical and theoretical foundations of AI. 
* Deadline: October 10, 2024; October 10, 2025; October 10, 2026
* Award: Approximately $500K-1.5M for durations up to three years


### [Campus Cyberinfrastructure (CC\*)](https://new.nsf.gov/funding/opportunities/campus-cyberinfrastructure-cc){target="_blank"}
* Supports coordinated campus-level networking and cyberinfrastructure improvements for science applications and distributed research projects.
  + Area (1) Data Driven Networking Infrastructure,
  + Area (2) Computing and the Computing Continuum,
  + Area (3) Network Integration and Applied Innovation,
  + Area (4) Data Storage and Digital Archives, and
  + Area (5) Strategy.
* Deadline: October 15, 2024
* Award: \$100K - \$1.4M depending on area for durations up to two years

### [Advanced Computing Systems & Services: Adapting to the Rapid Evolution of Science and Engineering Research 2.0](https://new.nsf.gov/funding/opportunities/advanced-computing-systems-services-adapting-rapid){target="_blank"}
* Supports organizations who are willing to serve as resource providers within the NSF Advanced Computing Systems and Services (ACSS) program.
* Deadline: October 29, 2024 (Category I, Capacity Resources); June 24, 2025 (Category II, Innovative Prototypes/Testbeds)
* Award: $10-20M for durations of five years (Category I); $5M for durations of five years (Category II)

### [Research on Innovative Technologies for Enhanced Learning (RITEL)](https://new.nsf.gov/funding/opportunities/research-innovative-technologies-enhanced-learning){target="_blank"}
* Supports early-stage research in emerging technologies such as AI, robotics and immersive or augmenting technologies for teaching and learning that respond to pressing needs in real-world educational environments.
* Deadline: November 5, 2024; November 4, 2025
* Award: $900K for durations up to three years

### [Collaborative Research in Computational Neuroscience (CRCNS)](https://new.nsf.gov/funding/opportunities/collaborative-research-computational-neuroscience){target="_blank"}
* Supports innovative approaches to science and engineering research on brain function, specifically collaborative activities that span a broad spectrum of computational neuroscience research, as appropriate to the missions and strategic objectives of each agency.
* Deadline: November 13, 2024; November 12, 2025
* Award: $250K/year for durations of three to five years

### [Ecology and Evolution of Infectious Diseases (EEID)](https://new.nsf.gov/funding/opportunities/ecology-evolution-infectious-diseases-eeid){target="_blank"}
* Supports the quantitative, mathematical, or computational understanding of pathogen transmission dynamics.
* Deadline: November 20, 2024, recurring on third Wednesday in November annually
* Award: $1.5-3M for durations of five years

### [Geoinformatics (GI)](https://new.nsf.gov/funding/opportunities/geoinformatics-gi){target="_blank"}
* Supports the deployment, operation, and sustainment of cyberinfrastructure (CI) resources to serve and support Earth Sciences research and education.
  + The *Innovative Resources track* supports the early-stage development, deployment, and community-building for CI resources that serve Earth Sciences research and education.
  + The *Sustained Resources track* supports the sustained operations and user community support for mature CI resources that serve Earth Sciences research and education.
* Deadline: *Sustained Resources* December 6, 2024, *Innovative Resources* December 5, 2025
* Award: *Innovative Resources* $200K/year for durations up to three years; *Sustained Resources* budget must align with the project scope, for durations of three to four years.

### [Human Networks and Data Science (HNDS)](https://new.nsf.gov/funding/opportunities/human-networks-data-science-hnds){target="_blank"}
*   Supports research that studies the behavior of individuals and groups by leveraging data and network science and the development of data infrastructure that makes such work possible.
*   Deadline: *Core Research* January 9, 2025, annually thereafter on the second Thursday in January and July; *Infrastructure* February 6, 2025, annually thereafter on the first Thursday in February and August
*   Awards: *Core Research* \$400K; *Infrastructure* \$800K for durations of one to five years

### [ACED: Accelerating Computing-Enabled Scientific Discovery](https://new.nsf.gov/funding/opportunities/aced-accelerating-computing-enabled-scientific){target="_blank"}
* Supports harnessing computing to accelerate scientific discovery, while driving new computing advancements. The intent is to catalyze advancements on both sides of a virtuous cycle that: (a) benefit scientific disciplines through computational technologies and (b) foster novel computing technologies that will enable advances beyond the specific use cases or domains originally targeted. 
* Deadline: January 14, 2025; recurring January 14 annually thereafter
* Award: $500K for durations of 18-24 months (Track I), $750K/year for durations up to four years (Track II)

### [Future Manufacturing (FM)](https://new.nsf.gov/funding/opportunities/future-manufacturing-fm){target="_blank"}
* Supports fundamental research, education, and training of a future workforce to overcome scientific, technological, educational, economic, and social barriers in order to catalyze new manufacturing capabilities that do not exist today. Focuses on cybermanufacturing, eco-manufacturing and biomanufacturing.
* Deadline:  January 13, 2025
* Award: $3M for up to four years (research grants); $500K for up to two years (seed)

### [Training-based Workforce Development for Advanced Cyberinfrastructure (CyberTraining)](https://new.nsf.gov/funding/opportunities/training-based-workforce-development-advanced){target="_blank"}
*   *Pilot* projects are exploratory activities that may lead to *Implementation* projects.
*   *Implementation* projects make CI training and educational activities or curriculum/instructional materials broadly accessible to a significant portion of a community for one or more disciplines.
*   Deadline: January 18, 2025, annually thereafter
*   Award: *Pilot* up to \$300K for durations up to two years; *Implementation* up to \$1M for durations up to four years

### [Strengthening the Cyberinfrastructure Professionals Ecosystem (SCIPE)](https://new.nsf.gov/funding/opportunities/strengthening-cyberinfrastructure-professionals){target="_blank"}
*   Supports projects that deepen the integration of cyberinfrastructure professionals' services into research, while fostering education, training and recognition that address CI workforce development needs.
*   Deadline: January 18, 2025, annually thereafter *Limited Submission Opportunity.*
*   Award: Not specified

### [Ethical and Responsible Research (ER2)](https://new.nsf.gov/funding/opportunities/ethical-responsible-research-er2){target="_blank"}
* Supports research on what constitutes and promotes responsible research conduct and how to instill that knowledge in researchers, practitioners and educators across all career stages.
* Deadline: January 23, 2025; fourth Thursday in January annually thereafter
* Award
  + Conference Projects: $50K and a maximum duration of 12 months.
  + Incubation Projects: $90K and a maximum duration of 12 months.
  + Research Grants: $400K and a maximum duration of 3 years.
  + Institutional Transformation Research Grants: $700K and a maximum duration of 5 years.

### [Mid-scale Research Infrastructure-1 (Mid-scale RI-1)](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-1-mid-scale-ri-1){target="_blank"}
* Supports the design and implementation of research infrastructure — including equipment, cyberinfrastructure, large-scale datasets and personnel — whose total project costs exceed NSF's Major Research Instrumentation program but are under $20 million.
* Deadline: January 2025 (anticipated, recurring every other year)
* Award: $4-20M for durations up to five years

### [Cognitive Neuroscience (CogNeuro)](https://new.nsf.gov/funding/opportunities/cognitive-neuroscience-cogneuro-0){target="_blank"}
* Supports advancement of our understanding of the neural mechanisms underlying human cognition and behavior. Funded proposals typically advance theories in cognitive neuroscience by relating precise and rich quantifications of physiology, cognition and behavior with each other (Intellectual Merit) and strengthen the field through, for example, outreach, mentoring the next generation of diverse cognitive neuroscientists and/or increasing awareness and utilization of the research the field produces (Broader Impacts).
* Deadline: February 3, 2025; February 1 and August 15 annually thereafter

### [Artificial Intelligence, Formal Methods, and Mathematical Reasoning (AIMing)](https://new.nsf.gov/funding/opportunities/artificial-intelligence-formal-methods){target="_blank"}
* Supports research at the interface of innovative computational and artificial intelligence (AI) technologies and new strategies/technologies in mathematical reasoning to automate knowledge discovery. 
* Deadline: February 5, 2025
* Award: $500K-$1.2M for up to three years

### [Science of Learning and Augmented Intelligence](https://new.nsf.gov/funding/opportunities/science-learning-augmented-intelligence){target="_blank"}
* Supports research to develop fundamental knowledge about principles, processes and mechanisms of learning and about augmented intelligence — how human cognitive function can be augmented through interactions with others and technology.
* Deadline: February 12, 2025 and August 6, 2025 (recurring annually) <!-- on the second Wed in Feb and the first Wed in August)-->

### [Incorporating Human Behavior in Epidemiological Models (IHBEM)](https://new.nsf.gov/funding/opportunities/incorporating-human-behavior-epidemiological-0){target="_blank"}
* Supports research that incorporates research on social and behavioral processes in mathematical epidemiological models. The program provides support for projects that involve balanced participation from the mathematical sciences and from the social, behavioral, and economic sciences.
* Deadline: February 1-14, 2025; recurring annually
* Award: $1M for durations of 3-4 years

### [Algorithms for Threat Detection (ATD)](https://new.nsf.gov/funding/opportunities/algorithms-threat-detection-atd){target="_blank"}
* Supports research on new ways to use spatiotemporal data to model human dynamics, with an emphasis on identifying and forecasting unusual events and future threats.
* Deadline: February 19, 2025; annually on the third Wednesday in February 
* Award: $150-300K

### [Enabling Discovery through GEnomics (EDGE)](https://new.nsf.gov/funding/opportunities/enabling-discovery-through-genomics-edge){target="_blank"}
* Supports research to advance understanding of comparative and functional genomics and the development of innovative tools, technologies, resources, and infrastructure that advance biological research focused on the identification of the causal mechanisms connecting genes and phenotypes.
* Deadline: February 20, 2025; recurring annually on the third Thursday in February
* Award: $2M for durations up to four years

### [NSF Scholarships in Science, Technology, Engineering, and Mathematics Program (S-STEM)](https://new.nsf.gov/funding/opportunities/nsf-scholarships-science-technology-engineering){target="_blank"}
*   Supports institutions of higher education to fund scholarships for academically talented low-income students and to study and implement a program of activities that support their recruitment, retention and graduation in STEM.
    *   Track 1: Institutional Capacity Building
    *   Track 2: Implementation: Single Institution
    *   Track 3: Inter-institutional Consortia
    *   Collaborative Planning Grants to Develop an Inter-institutional Consortium
*   Deadline: March 5, 2025, annually thereafter
*   Award: *Track 1 (Institutional Capacity Building)* \$1M for a duration of up to six years; *Track 2 (Implementation: Single Institution)* \$2.5M for a duration of up to six years; *Track 3 (Inter-institutional Consortia)* \$5M for a duration of up to six years; *Collaborative Planning* \$100K for a duration of one year.

### [Mathematical Foundations of Digital Twins (MATH-DT)](https://new.nsf.gov/funding/opportunities/mathematical-foundations-digital-twins-math-dt){target="_blank"}
* Supports foundational mathematical and statistical research on digital twins in applied science to harness science, technology and innovation to address society’s most pressing challenges.
* Deadline: March 17, 2025; March 15 annually thereafter
* Award: Approximately $500-800K for durations up to three years

### [Improving Undergraduate STEM Education: Computing in Undergraduate Education (IUSE: CUE)](https://new.nsf.gov/funding/opportunities/improving-undergraduate-stem-education-computing){target="_blank"}
* Supports partnerships to re-envision computing education to serve a broad group of students, in a scalable manner, with an emphasis on broadening the participation of groups who are underrepresented and underserved by traditional computing courses and careers.
* Deadline: April 29, 2025; recurring on last Tuesday in April annually
* Award: $1-2M for up to two years
* [EducateAI and Computing in Undergraduate Education (IUSE:CUE) Webinar](https://new.nsf.gov/events/educateai-computing-undergraduate-education){target="_blank"} on May 9 at 12pm MT.

### [Foundations for Digital Twins as Catalyzers of Biomedical Technological Innovation (FDT-BioTech)](https://new.nsf.gov/funding/opportunities/foundations-digital-twins-catalyzers-biomedical){target="_blank"}
* Supports inherently interdisciplinary research projects that underpin the mathematical and engineering foundations behind the development and use of digital twins and synthetic data in biomedical and healthcare applications, with a particular focus on digital, in silico models used in the evaluation of medical devices and the relevance of the developed models in addressing current and emerging  challenges affecting the development and assessment of biomedical technologies. 
* Deadline: May 5, 2025; recurring the first Monday in May annually
* Award: $1M or less for durations up to three years

### [Mid-scale Research Infrastructure-2 (Mid-scale RI-2)](https://new.nsf.gov/funding/opportunities/mid-scale-research-infrastructure-2-mid-scale-ri-2){target="_blank"}
*   Supports the implementation of research infrastructure --- including equipment, cyberinfrastructure, large-scale datasets and personnel --- whose total project costs fall between \$20 million and \$100 million.
*   Deadline: May 2025 (LOI), June 2025 (Preliminary Proposal); dates anticipated, recurring every other year
*   Award: \$20-100M for durations up to five years

### [CyberCorps Scholarship for Service (SFS)](https://new.nsf.gov/funding/opportunities/cybercorps-scholarship-service-sfs-0){target="_blank"}
* Supports scholarships in cybersecurity that require a service obligation following graduation equivalent to the length of the scholarship.
* Deadline: July 15, 2025; annually thereafter on July 15
* Award: Full scholarship for undergraduate and graduate students in cybersecurity for durations up to three years

### [Research Security and Integrity Information Sharing Analysis Organization (RSI-ISAO)](https://new.nsf.gov/funding/opportunities/research-security-integrity-information-sharing){target="_blank"}
* Supports the establishment of an independent Research Security and Integrity Information Sharing Analysis Organization (RSI-ISAO) to empower the U.S. research community (institutions of higher education (IHEs), non-profit research institutions, and small and medium-sized for-profit organizations) to address foreign government interference, support security-informed decision-making, and serve as a conduit that connects research community stakeholders with one another and with U.S. government (USG) agencies via NSF.
* Deadline: September 2025 (LOI), October 2025 (Proposal); anticipated dates
* Award: $9.5M for FY2024 then at least $10M/year for durations up to five years

### [National Artificial Intelligence (AI) Research Institutes](https://new.nsf.gov/funding/opportunities/national-artificial-intelligence-research){target="_blank"}
* Supports the development of new AI Institutes.
* Deadline: Expected early 2026
* Award: $16-20M for durations of four or five years

### [Expeditions in Computing (Expeditions)](https://new.nsf.gov/funding/opportunities/expeditions-computing-expeditions){target="_blank"}
*   Supports long-term, multi-institutional research with the potential to transform computer and information science and engineering.
*   Deadline: *Preliminary Proposal* June 19, 2026; *Full Proposal* March 31, 2027
*   Award: \$15M for durations up to seven years


### Dear Colleague Letters
* [National Artificial Intelligence Research Resource (NAIRR) Pilot Demonstration Projects](https://www.nsf.gov/pubs/2024/nsf24093/nsf24093.jsp){target="_blank"} The NAIRR has been launched as a proof of concept to demonstrate the value and potential impact of the NAIRR concept as described in the [NAIRR Task Force Report](https://www.ai.gov/wp-content/uploads/2023/01/NAIRR-TF-Final-Report-2023.pdf){target="_blank"}. Activities aligned with the NAIRR Pilot vision include facilitating researcher and educator requests for computing, model access, and other resources; integrating data, software, platforms, and tools; reaching new and broad communities; fostering positive end user experiences; and building a NAIRR pilot user community. <!-- May 28, 2023 -->
* [Leveraging Cyberinfrastructure for Research Data Management (RDM)](https://www.nsf.gov/pubs/2024/nsf24085/nsf24085.jsp){target="_blank"} NSF invites Early-Concept Grants for Exploratory Research (EAGER) and conference/workshop proposals that aim to leverage cyberinfrastructure to advance research data management (RDM) and public access to research data in alignment with the goals of OAC's [Cyberinfrastructure for Public Access and Open Science (CI PAOS) program](https://new.nsf.gov/funding/opportunities/cyberinfrastructure-public-access-open-science-ci){target="_blank"} and the [NSF Public Access Initiative (PAI)](https://new.nsf.gov/public-access){target="_blank"}.  <!-- May 1, 2024 -->
* [Using Long-Term Research Associated Data (ULTRA-Data)](https://www.nsf.gov/pubs/2024/nsf24081/nsf24081.jsp){target="_blank"} NSF seeks to stimulate and encourage the use and reuse of data from environmental time series research to improve generalizable understanding in fields including (but not limited to) ecology, organismal evolution/adaptation, geoscience, and oceanography. <!--April 23, 2024-->
* [Catalyzing human-centered solutions through research and innovation in science, the environment and society](https://new.nsf.gov/funding/opportunities/catalyzing-human-centered-solutions-through-0){target="_blank"} NSF invites planning proposals for interdisciplinary research to create evidence-based solutions that strengthen human resilience, security, and quality of life by addressing seemingly intractable challenges that confront society. Concept outlines should be submitted by *May 1, 2024* with invited full proposals due *July 1, 2024*. <!-- March 28, 2024 -->
* [Innovative Use of Scientific Collections (IUSC)](https://www.nsf.gov/pubs/2024/nsf24069/nsf24069.jsp){target="_blank"} <!--March 18, 2024-->
* [Supporting Computing & Networking Research for a National Discovery Cloud for Climate (NDC-C)](https://www.nsf.gov/pubs/2024/nsf24058/nsf24058.jsp){target="_blank"}  <!-- February 20, 2024 -->
* [NSF-Italian Ministry of Universities and Research Lead Agency Opportunity on Artificial Intelligence](https://www.nsf.gov/pubs/2024/nsf24055/nsf24055.jsp){target="_blank"}  <!-- February 20, 2024 -->
* [Funding Opportunities for Engineering Research in Artificial Intelligence](https://www.nsf.gov/pubs/2024/nsf24039/nsf24039.jsp){target="_blank"} <!-- December 22, 2023 -->

* [Broadening Participation in Computing (BPC) Supplemental Funding in Computer and Information Science and Engineering](https://www.nsf.gov/pubs/2024/nsf24030/nsf24030.jsp){target="_blank"} recommended submission prior to March 31 each year. <!-- December 5, 2023 -->

* [Advancing education for the future AI workforce (EducateAI)](https://www.nsf.gov/pubs/2024/nsf24025/nsf24025.jsp){target="_blank"} With this Dear Colleague Letter (DCL), EDU and CISE encourage the submission of novel and high impact proposals that advance inclusive computing education that prepares preK-12 and undergraduate students for the AI workforce.<!-- December 1, 2023-->

* [Medical / Health Cyber Physical Systems Proposals](https://www.nsf.gov/pubs/2024/nsf24017/nsf24017.jsp){target="_blank"}<!-- November 8, 2023 -->

* [Workshops to Identify Educational Requirements of the Future Ocean Technical Workforce](https://www.nsf.gov/pubs/2023/nsf23134/nsf23134.jsp){target="_blank"} <!-- July 21, 2023 -->

* [Stimulating Diversification in Language Science Research (LangDiv)](https://www.nsf.gov/pubs/2023/nsf23103/nsf23103.pdf){target="_blank"} <!-- May 10, 2023 -->

* [Interdisciplinary REU Sites at the Intersection of Computing and Communication Foundations and Mathematics and Statistics](https://new.nsf.gov/funding/opportunities/interdisciplinary-reu-sites-intersection-computing){target="_blank"} <!-- April 4, 2023 -->

* [Advancing Research in the Geosciences Using Artificial Intelligence (AI) and Machine Learning (ML)](https://new.nsf.gov/funding/opportunities/advancing-research-geosciences-using-artificial){target="_blank"} <!-- Jan 20, 2023 -->

* [Cyberinfrastructure, Data and Computation Opportunities for CMMI](https://new.nsf.gov/funding/opportunities/cyberinfrastructure-data-computation-opportunities){target="_blank"} <!-- Oct 24, 2022 -->

* [Stimulating Integrative Research in Computational Cognition (CompCog)](https://new.nsf.gov/funding/opportunities/stimulating-integrative-research-computational-1){target="_blank"} <!--June 2, 2022-->

* [Advancing Discovery with AI-Powered Tools (ADAPT) in the Mathematical and Physical Sciences](https://www.nsf.gov/pubs/2021/nsf21080/nsf21080.jsp){target="_blank"} <!-- May 5, 2021 -->

* [Fairness, Ethics, Accountability, and Transparency: Enabling Breakthrough Research to Expand Inclusivity in Computer and Information Science and Engineering Research](https://www.nsf.gov/pubs/2019/nsf19016/nsf19016.jsp){target="_blank"} <!-- Nov 2, 2018 -->


Updated August 14, 2024.
