---
title: "NIH Funding Opportunities"
---
<!-- ### [](){target="_blank"}
* S
* Deadline: 
* Award: , $ for durations up to  years -->
## Cooperative Agreement (U) Grants

### [BRAIN Initiative: Development of Novel Tools to Probe Cell-Specific and Circuit-Specific Processes in Human and Non-Human Primate Brain](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-295.html){target="_blank"}
* Supports the development and validation of novel tools to facilitate the detailed analysis and manipulation of complex circuits in large brains. Critical advances in the treatment of brain disorders in human populations are hindered by our lack of ability to monitor and manipulate circuitry in safe, minimally-invasive ways. 
* Deadline: May 8, 2024 (LOI), June 7, 2024 (Proposal)
* Award: UG3/UH3, budget must align with the project scope, for durations up to five years (UG3 cannot exceed three years)

### [Broadening Opportunities for Computational Genomics and Data Science Education](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-002.html){target="_blank"}
* Supports faculty members at institutions with a mission to serve historically underrepresented populations in biomedical research to develop undergraduate and master’s degree-level educational content in computational genomics, data science, or a combination of these topics.
* Deadline: May 10, 2024 (LOI); June 10, 2024 (Proposal)
* Award: UE5, $150K/year (direct) for three years

### [Early-Stage Development of Informatics Technologies for Cancer Research and Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-24-017.html){target="_blank"}
* Supports the development of enabling informatics technologies to improve the acquisition, management, analysis, and dissemination of data and knowledge across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and/or cancer health disparities. 
* Deadline:  May 11, 2024 (LOI), June 11, 2024 (Proposal)
* Award: U01, $300K/year (direct) for durations of three years

### [Advanced Development of Informatics Technologies for Cancer Research and Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-24-018.html){target="_blank"}
* Supports advanced development and enhancement of emerging informatics technologies to improve the acquisition, analysis, visualization, and interpretation of data across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and cancer health disparities.
* Deadline:  May 11, 2024 (LOI), June 11, 2024 (Proposal)
* Award: U24, $600K/year (direct) for durations of five years

### [BRAIN Initiative: Exploratory Team-Research BRAIN Circuit Programs - eTeamBCP](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-23-025.html){target="_blank"}
* Supports teams of three or more (up to six) PDs/PIs that seek to cross boundaries of interdisciplinary collaboration to elucidate the contributions of dynamic circuit activity to a specific behavioral or neural system.
* Deadline: May 14, 2024 (LOI), June 14, 2024 (Proposal)
* Award: U01, approximately $2.4M/year for durations of three  years

### [Use of Digital Health Technologies in Clinical Investigations to Support Drug and Biological Product Development](https://grants.nih.gov/grants/guide/rfa-files/RFA-FD-24-037.html){target="_blank"}
* Supports addressing topics related to the use of digital health technologies (DHTs) for remote data acquisition in clinical investigations to support drug development.
* Deadline: May 20, 2024
* Award: U01, $1.1M during year one and $860K during year two

### [Center of Excellence for Systems Modeling of Infection and Immunity across Biological Scales](https://grants.nih.gov/grants/guide/rfa-files/RFA-AI-23-077.html){target="_blank"}
* Supports the establishment of one (1) Center of Excellence (CoE) to coordinate the research community of infectious and immune-mediated disease (IID) computational modelers and advance IID modeling research across biological scales.
* Deadline: May 31, 2024 (LOI), June 30, 2024 (Proposal)
* Award: U54, $3.125M for durations of five years

### [HEAL Initiative: Interdisciplinary Team Science to Uncover the Mechanisms of Pain Relief by Medical Devices](https://grants.nih.gov/grants/guide/rfa-files/rfa-ns-23-003.html){target="_blank"}
* Supports interdisciplinary research teams of multiple PDs/PIs to investigate the mechanism of action of pain relief by medical devices with the overall goal of optimizing therapeutic outcomes for FDA-approved or -cleared technologies. 
* Deadline: June 10, 2024 and June 9, 2025
* Award: RM1, generally $1.5M/year (direct) for durations up to five years

### [Coordinating Center to Support Multi-Sectoral Preventive Interventions that Address Social Determinants of Health in Populations that Experience Health Disparities](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-24-006.html){target="_blank"}
* Supports a Coordinating Center (CC) for the Multi-Sectoral Preventive Interventions (MSPI) Research Network. Members of the Multi-Sectoral Preventive Interventions (MSPI) Research Network, including the CC and separately funded research projects, will work collaboratively with the NIH to test prospective multi-sectoral preventive interventions that address social determinants of health in populations that experience health disparities.  
* Deadline: July 5, 2024 (LOI), August 5, 2024 (Proposal)
* Award: U24, $1M/year (direct) for durations up to seven years

### [Multi-sectoral preventive interventions that address social determinants of health in populations that experience health disparities](https://grants.nih.gov/grants/guide/pa-files/PAR-24-053.html){target="_blank"}
* Supports projects to test prospective multi-sectoral preventive interventions that address social determinants of health in populations that experience health disparities. These research projects will be part of the Multi-Sectoral Preventive Interventions (MSPI) Research Network, which will also include a Coordinating Center ([RFA-OD-24-006](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-24-006.html){target="_blank"}).   
* Deadline: July 5, 2024 (LOI), August 5, 2024 (Proposal)
* Award: UG3/UH3, $500K/year (direct) for two years (UG3, phase 1) and $750K/year (direct) for five years (UH3, phase 2)

### [ML/AI Tools to Advance Genomic Translational Research (MAGen) - Coordinating Center](https://grants.nih.gov/grants/guide/notice-files/NOT-HG-24-030.html){target="_blank"}
* Supports the development of novel Machine Learning/Artificial Intelligence (ML/AI) tools to explore their potential for advancing genomic translational research. The MAGen CC will be responsible for implementing approaches to bring diverse teams together to enable synergistic and collaborative team science across the Consortium. 
* Deadline: July 26, 2024 (expected) 
* Award: UG3/UH3, $800K/year (direct) for two years (UG3) and $800K/year (direct) for three years (UH3)

### [ML/AI Tools to Advance Genomic Translational Research (MAGen) - Development Sites](https://grants.nih.gov/grants/guide/notice-files/NOT-HG-24-029.html){target="_blank"}
* Supports the development of novel Machine Learning/Artificial Intelligence (ML/AI) tools to explore their potential for advancing genomic translational research. Each MAGen Site will develop and cross validate tools, conduct ELSI research projects, and generate resources for dissemination.
* Deadline: July 26, 2024 (expected) 
* Award: UG3/UH3, $1.6M/year (total) for two years (UG3) and $1.6M/year (direct) for three years (UH3)

### [Enhancement and Management of Established Biomedical Data Repositories and Knowledgebases](https://grants.nih.gov/grants/guide/pa-files/PAR-23-237.html){target="_blank"}
* Supports established biomedical data repositories and knowledgebases as distinct and separate resources that have demonstrated impact and have potential for continued benefit to the community served. 
* Deadline: July 27, 2024 (LOI), September 25, 2024 (Proposal) and November 26, 2024 (LOI), January 25, 2025 (Proposal); annually through January 2026
* Award: U24, budget must align with the project scope for durations up to 5 years
* Pre-Application Webinar on June 26, 2024, 9-10am MT, register in advance [here](https://scgcorp.zoom.us/webinar/register/WN_uFo6N3LoQPCtcqtrWO9LEw#/registration){target="_blank"}.

### [Collaborative Opportunities for Multidisciplinary, Bold, and Innovative Neuroscience (COMBINE)](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-23-027.html){target="_blank"}
* Supports integrated efforts of three to six PDs/PIs to pursue a bold, impactful, and challenging goal with defined 5-year outcomes within the scope of this program and the NINDS mission. This defined research goal must only be achievable by an interdisciplinary team approach involving innovative combination of distinct disciplines and/or intellectual viewpoints, synergy in expertise and approaches, and well-managed team interactions. 
* Deadline: September 8, 2024 (LOI), October 8, 2024 (Proposal)
* Award: RM1, $500K-$1.5M (direct) for durations up to five years

### [Precision Mental Health: Develop Tools to Inform Treatment Selection in Depression](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-25-190.html){target="_blank"}
* Supports creation of a pipeline to accelerate the development and early validation of predictive tools and/or biomarkers to inform individual-level treatment selection among two or more existing therapeutics for depression.
* Deadline: September 18, 2024 (LOI), October 18, 2024 (Full Proposal)
* Award: UG3/UH3; $500K/year (direct) for one to two years (UG3, phase 1) and $1.5M/year (direct) for five years (UH3, phase 2)

### [ClinGen Genomic Curation Expert Panels](https://grants.nih.gov/grants/guide/pa-files/PAR-23-199.html){target="_blank"}
* Supports the establishment of Expert Panels that will select genes and genomic variants associated with diseases or conditions of high priority to participating NIH Institutes and Centers (ICs) and systematically determine their clinical significance for diagnosis and treatment of these diseases or conditions. 
* Deadline: April 25, 2025 (LOI), May 25, 2025 (Proposal)
* Award: U24, $220K/year (direct) for durations up to three years



## Program and Center (P) Grants
### [Silvio O. Conte Centers for Basic Neuroscience or Translational Mental Health Research](https://grants.nih.gov/grants/guide/pa-files/PAR-22-155.html){target="_blank"}
* Supports teams of researchers working at different levels of analysis and employing integrative, novel, and creative experimental approaches to address high-risk, high-impact questions with the primary objectives of: (a) advancing the state of the science in basic brain and behavior research that will uncover and dissect the underlying mechanisms that will ultimately provide the foundation for understanding mental disorders; (b) supporting the integration and translation of basic and clinical neuroscience research on severe mental illnesses; and/or (c) advancing our understanding of the neurobehavioral developmental mechanisms and trajectories of psychopathology that begin in childhood and adolescence.
* Deadline: June 7, 2024 and June 9, 2025
* Award: P50, $2M/year (direct) for durations up to five years




## Career Development and Training (F/K and T) Grants
### [Predoctoral Training in Advanced Data Analytics for Behavioral and Social Sciences Research (BSSR)](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-24-012.html){target="_blank"}
* Supports predoctoral training programs that focus on innovative computational and/or data science analytic approaches and their incorporation into training for the future BSSR health research workforce.
* Deadline: May 24, 2024
* Award: T32, budgets need to reflect the actual needs of the proposed project, durations up to five years

### [INCLUDE (INvestigation of Co-occurring conditions across the Lifespan to Understand Down syndromE) Predoctoral to Postdoctoral Fellow Transition Award](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-24-007.html){target="_blank"}
* Supports exceptional graduate students from a broad variety of research fields to pursue postdoctoral training focused on Down syndrome related research. Graduate students from disciplines including, but not limited to, genetics, biochemistry, data science, imaging, engineering, and neurobiology are invited to apply to this opportunity.
* Deadline: June 1, 2024 (LOI); July 1, 2024 (Proposal); recurring on July 1, 2025 and 2026
* Award: F99/K00, budgets composed of stipends, tuition/fees, institutional allowances for up to two years (F99) followed by four years (K00)






## Research Grants - R01 Activities
### [Leveraging Health Information Technology (Health IT) to Address and Reduce Health Care Disparities](https://grants.nih.gov/grants/guide/pa-files/PAR-22-145.html){target="_blank"}
* Supports research that examines the impact of leveraging health information technology (health IT) to reduce disparities in access to and utilization of health care services, patient-clinician communication, and health outcomes for populations that experience health disparities in the U.S.
* Deadline: May 6, 2024 (LOI), June 5, 2024 (Proposal); annually in February, June, and October through Feb 2025
* Award: R01, budget must align with the project scope, for durations up to five years

### [Accelerating the Pace of Child Health Research Using Existing Data from the Adolescent Brain Cognitive Development (ABCD) Study](https://grants.nih.gov/grants/guide/pa-files/PAR-22-137.html){target="_blank"}
* Supports the  analysis of the Adolescent Brain Cognitive Development (ABCD) dataset to increase knowledge of adolescent health and development. 
* Deadline: May 6, 2024 (LOI), June 5, 2024 (Proposal); annually in February, June, October through Feb 2025
* Award: R01, $250K/year (direct) for durations up to five years ([R21](https://grants.nih.gov/grants/guide/pa-files/PAR-22-138.html){target="_blank"} also available)

### [NLM Research Grants in Biomedical Informatics and Data Science](https://grants.nih.gov/grants/guide/pa-files/PAR-23-034.html){target="_blank"}
* Supports innovative research and development in biomedical informatics and data science. This funding opportunity focuses on biomedical discovery and data-powered health, integrating streams of complex and interconnected research outputs that can be translated into scientific insights, clinical care, public health practices, and personal wellness.
* Deadline: May 6, 2024 (LOI), June 5, 2024 (Proposal); annually in February, June, and October through 2025
* Award: R01, $250K/year (direct) for durations up to four years

### [Secondary Analysis and Integration of Existing Data to Elucidate Cancer Risk and Related Outcomes](https://grants.nih.gov/grants/guide/pa-files/PAR-23-254.html){target="_blank"}
* Supports secondary data analysis and integration of existing datasets and database resources, with the ultimate aim to elucidate cancer risk and related outcomes (e.g., risk prediction or reduction, survival, or response to treatment, etc.). 
* Deadline: May 6, 2024 (LOI), June 5, 2024 (Proposal); recurring annually in February, June, and October through June 2026
* Award: R01, $350K/year (direct) for durations of up to five years ([R21](https://grants.nih.gov/grants/guide/pa-files/PAR-23-255.html){target="_blank"} also available)

### [Multi-Scale Models Bridging Levels of Analysis in Aging and Alzheimer's Disease (AD) and AD-Related Dementias (ADRD)](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-25-016.html){target="_blank"}
* Supports establishment of multi-scale computational models recapitulating dynamic changes associated with aging and Alzheimer’s disease (AD) and AD-related dementias (ADRD). 
* Deadline: May 13, 2024 (LOI), June 13, 2024 (Proposal)
* Award: R01, $500K/year (direct) for durations up to five years

### [BRAIN Initiative: Targeted BRAIN Circuits Projects- TargetedBCP](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-23-024.html){target="_blank"}
* Supports research projects that seek to understand how circuit activity gives rise to mental experience and behavior using innovative, methodologically-integrated approaches.
* Deadline: May 28, 2024 (LOI), June 28, 2024 (Proposal), recurring on October 2, 2024
* Award: R01, approximately $750K/year for durations up to five years

### [Leveraging Data at Scale to Understand Natural Product Impacts on Whole Person Health](https://grants.nih.gov/grants/guide/rfa-files/RFA-AT-24-008.html){target="_blank"}
* Supports development, adaptation, and/or applications of computational tools to aggregate and analyze orthogonal chemical and/or biological data sets related to natural products with the aim of generating novel testable hypotheses regarding their biological activity and role in the context of whole person health research.
* Deadline: May 28, 2024 (LOI), June 28, 2024 (Proposal)
* Award: R01, $500K (direct) for durations up to five years

### [Modular R01s in Cancer Control and Population Sciences](https://grants.nih.gov/grants/guide/pa-files/PAR-24-122.html){target="_blank}
* Supports research efforts on novel scientific ideas that have the potential to substantially advance cancer research in statistical and analytic methods, epidemiology, cancer survivorship, cancer-related behaviors and behavioral interventions, health care delivery, digital health and data science, and implementation science.
* Deadline: June 5, 2024, October 5, 2024
* Award: R01, $250K/year (direct) for durations up to five years

### [Investigator Initiated Research in Computational Genomics and Data Science](https://grants.nih.gov/grants/guide/pa-files/PAR-21-254.html){target="_blank"}
* Supports a broad range of research efforts in computational genomics, data science, statistics, and bioinformatics relevant to one or both of basic or clinical genomic science, and broadly applicable to human health and disease.
* Deadline: June 5, 2024
* Award: R01, $500K/year (direct) for durations of up to five years ([R21](https://grants.nih.gov/grants/guide/pa-files/PAR-21-255.html){target="_blank"} also available)

### [NIDCR Research Grants for Analyses of Existing Genomics Data](https://grants.nih.gov/grants/guide/pa-files/PAR-23-133.html){target="_blank"}
* Supports meritorious research projects that address research questions relevant to human dental, oral, or craniofacial (DOC) biology, and diseases and conditions, through analysis of existing and publicly available genomic data, with or without other types of complementary data, using statistical and computational approaches.
* Deadline: June 5, 2024, recurring annually in February, June, and October through February 2026
* Award: R01, budget must align with the project scope, for durations of up to three years. ([R03 Opportunity](https://grants.nih.gov/grants/guide/pa-files/PAR-23-132.html){target="_blank"} also available.)

### [Personal Health Informatics for Delivering Actionable Insights to Individuals](https://grants.nih.gov/grants/guide/pa-files/PAR-23-245.html){target="_blank"}
* Supports development of novel informatics and data science approaches that can help individuals understand and improve their health through actionable insights.
* Deadline: June 5, 2024, recurring annually in February, June, and October through October 2026
* Award: R01, $250K/year (direct) for durations of up to four years 

### [Academic-Industrial Partnerships (AIP) to Translate and Validate In Vivo Imaging Systems](https://grants.nih.gov/grants/guide/pa-files/PAR-23-259.html){target="_blank"}
* Supports translation of scientific discoveries and engineering developments in imaging, data science and/or spectroscopic technologies into methods or tools that address contemporary problems in understanding the fundamental biology, potential risk of development, diagnosis, or treatment of cancer.
* Deadline: June 5, 2024, recurring annually in February, June, and October through October 2026
* Award: R01, $500K/year (direct) for durations of up to five years 

### [Imaging, Biomarkers and Digital Pathomics for the Early Detection of Premetastatic Cancer and Precancerous Lesions Associated with Lethal Phenotypes](https://grants.nih.gov/grants/guide/pa-files/PAR-22-131.html){target="_blank"}
* Supports the development of state-of-the-art projects that integrate imaging, biomarkers, digital pathomics, glycomics, metabolomics, other omic information and/or meta data obtained from platforms including but not limited to lower resolution diagnostic acquisitions and systemic biomarker results to high resolution single-cell analytics / imaging applied to the characterization of heterogeneous cell populations within tumor for improving current approaches for: (1) the early detection of organ confined premetastatic aggressive cancer, and, (2) identifying precancerous lesions associated with the development of a subsequent lethal phenotype.
* Deadline: June 5, 2024; recurring annually in February, June, and October through June 2025
* Award: R01, budget must reflect actual needs of the proposed project, durations up to five years

### [New Approaches for Measuring Brain Changes Across Longer Timespans](https://grants.nih.gov/grants/guide/pa-files/PAR-24-160.html){target="_blank"}
* Supports multidisciplinary investigators to develop new approaches or apply existing approaches in novel ways to measure brain activity, connectivity, genomics, or other aspects across the age spectrum of neurodevelopment.
* Deadline: June 5, 2024; recurring in February, June, and October through February 2027
* Award: R01, budget must reflect actual needs of the proposed project, durations up to five years; [R21 opportunity also open](https://grants.nih.gov/grants/guide/pa-files/PAR-24-161.html){target="_blank"}

### [Focused Technology Research and Development](https://grants.nih.gov/grants/guide/pa-files/PAR-22-127.html){target="_blank"}
* Supports projects that focus solely on the development of technologies with the potential to enable acquisition of biomedical knowledge. Projects should be justified in terms of technical innovation and utility of such technical innovation for impacting future biomedical research. 
* Deadline: June 5, 2024; recurring in February, June, and October through February 2025
* Award: R01, budget must reflect actual needs of the proposed project, durations up to five years [R21 Opportunity also available.](https://grants.nih.gov/grants/guide/pa-files/PAR-22-126.html){target="_blank"}

### [Ethical, Legal and Social Implications (ELSI) Research](https://grants.nih.gov/grants/guide/pa-files/PAR-23-293.html){target="_blank"}
* Supports the study of the ethical, legal and social implications (ELSI) of human genome research, using either single or mixed methods.
* Deadline: June 18, 2024; recurring annually in February, June, and October through October 2026
* Award: R01, budget must align with the project scope, for durations of three to five years ([R21](https://grants.nih.gov/grants/guide/pa-files/PAR-23-294.html){target="_blank"} and [R03](https://grants.nih.gov/grants/guide/pa-files/PAR-23-295.html){target="_blank"} also available)

### [Advancing Genomic Medicine Research](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-032.html){target="_blank"}
* Supports proposals that stimulate innovation and advance understanding of when, where, and how best to implement the use and sharing of genomic information and technologies in clinical care  provided to all persons irrespective of racial/ethnic background or socioeconomic status.
* Deadline: July 8, 2024; February 11, 2025
* Award: R01, $500K/year (direct) for durations up to five years([R21 Opportunity](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-033.html){target="_blank"} also available)

### [BRAIN Initiative: Theories, Models and Methods for Analysis of Complex Data from the Brain](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-23-039.html){target="_blank"}
* Supports the development of theories, computational models, and analytical tools to derive understanding of brain function from complex neuroscience data.
* Deadline: August 13, 2024 (LOI), September 12, 2024 (Proposal) 
* Award: R01, approximately $150-250K for durations up to three years

### [Addressing the Impact of Structural Racism and Discrimination on Minority Health and Health Disparities](https://grants.nih.gov/grants/guide/pa-files/PAR-23-112.html){target="_blank"}
* Supports intervention research that addresses structural racism and discrimination (SRD) in order to improve minority health or reduce health disparities.
* Deadline: September 9, 2024 (LOI), October 9, 2024 (Proposal), recurring October 9, 2025 
* Award: R01, $500K/year (direct) for durations up to five years 

### [BRAIN Initiative: Research on the Ethical Implications of Advancements in Neurotechnology and Brain Science](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-25-170.html){target="_blank"}
* Supports efforts addressing core ethical issues associated with research focused on the human brain and resulting from emerging technologies and advancements supported by the BRAIN Initiative. 
* Deadline: September 11, 2024 (LOI), October 11, 2024 (Proposal); recurring on October 10, 2025 and October 9, 2026
* Award: R01, $300K/year (direct) for durations up to four years; [R21 Opportunity](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-25-171.html){target="_blank"} is also available.



## Research Grants - Other Activities

### [Solutions to Enable Regional Genomic Medicine eConsult Services](https://grants.nih.gov/grants/guide/pa-files/PAR-24-106.html){target="_blank"}
* Supports Small Business Technology Transfer (STTR)/Small Business Innovation Research (SBIR) grant applications from small businesses to develop innovative solutions for commercialization that would enable regional genomic medicine eConsult Services.
* Deadline: April 30, 2024 (LOI), May 30, 2024 (Proposal)
* Award: [R41/R42](https://grants.nih.gov/grants/guide/pa-files/PAR-24-107.html){target="_blank"} or [R43/44](https://grants.nih.gov/grants/guide/pa-files/PAR-24-106.html){target="_blank"}; $400K (total) for durations up to two years for Phase I, $2.15M (total) for durations up to three years for Phase II

### [Research Experience in Genomic Research for Data Scientists](https://grants.nih.gov/grants/guide/pa-files/PAR-21-075.html){target="_blank"}
* Supports educational activities that encourage individuals from diverse backgrounds, including those from groups underrepresented in the biomedical and behavioral sciences, to pursue further studies or careers in research.
* Deadline: [Anticipated May 2024](https://www.genome.gov/sites/default/files/media/files/2023-09/Genomic_Research_Experiences_for_Data_Scientists_R25_PAR.pdf){target="_blank"}
* Award: R25, $250K/year (direct) for durations up to five years

### [Development of Innovative Informatics Methods and Algorithms for Cancer Research and Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-24-016.html){target="_blank"}
* Supports innovative informatics methods and algorithms to improve the acquisition, analysis, visualization, or interpretation of data across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and/or cancer health disparities.
* Deadline: May 11, 2024 (LOI), June 11, 2024 (Proposal)
* Award: R21, $275K (direct) for durations up to two years

### [Advancing Learning Health Care Research in Outpatient Mental Health Treatment Settings](https://grants.nih.gov/grants/guide/pa-files/PAR-24-118.html){target="_blank"}
* Supports exploratory/developmental research applications within the learning health care framework to support adoption, implementation, sustainability, and continuous improvement of evidence-based practices in outpatient mental health and substance use treatment systems.
* Deadline: May 16, 2024 (LOI), June 16, 2024 (Proposal); recurring every February, June, and October through October 2025
* Award: R34, $450K (direct) for durations up to three years

### [BRAIN Initiative: Targeted BRAIN Circuits Planning Projects – TargetedBCPP](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-23-023.html){target="_blank"}
* Supports research projects that offer a limited scope of aims and an approach that will establish feasibility, validity, or other technically qualifying results that, if successful, would support, enable, and/or lay the groundwork for a potential, subsequent Targeted BRAIN Circuits Projects - Targeted BCP R01.
* Deadline: May 28, 2024 (LOI), June 28, 2024 (Proposal), recurring October 2, 2024
* Award: R34, $450K for durations up to two years

### [Developing Novel Theory and Methods for Understanding the Genetic Architecture of Complex Human Traits](https://grants.nih.gov/grants/guide/pa-files/PAR-23-301.html){target="_blank"}
* Supports applications for novel theory and methods development that enable better understanding of how genetic and non-genetic factors contribute to complex trait variation across individuals, families, and populations.
* Deadline: June 16, 2024, recurring February, June, and October 16 through October 2026
* Award: R21, $275K total (direct) for durations up to two years

### [NEI Research Grant for Vision-Related Secondary Data Analysis](https://grants.nih.gov/grants/guide/pa-files/PAR-22-141.html){target="_blank"}
* Supports vision-related secondary data analyses utilizing existing database resources.
* Deadline: June 16, 2024 annually in February, June, and October through Feb 2025 <!-- on the 16th -->
* Award: R21, $275K (direct) for durations up to two years

### [BRAIN Initiative: Data Archives for the BRAIN Initiative](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-25-110.html){target="_blank"}
* Supports applications to develop web-accessible data archives to capture, store, and curate data related to the Brain Research Through Advancing Innovative Neurotechnologies® (BRAIN) Initiative activities. 
* Deadline: June 24, 2024; recurring June 24, 2025 and June 24, 2026
* Award: R24; budget must align with the project scope, for durations of up to five years

### [Using Archived Data and Specimen Collections to Advance Maternal and Pediatric HIV/AIDS Research](https://grants.nih.gov/grants/guide/rfa-files/RFA-HD-25-009.html){target="_blank"}
* Supports utilization of archived HIV/AIDS data and biospecimen collections to generate new research questions and findings related to epidemiology, pathogenesis, treatment, prevention, clinical manifestations, and HIV-associated co-infections in maternal, pediatric, and adolescent populations.
* Deadline: June 24, 2024 (LOI), July 24, 2024 (Proposal)
* Award: R21; $275K (direct) over two years

### [Harnessing Artificial Intelligence and Polypharmacology to Discover Pharmacotherapeutics for Substance Use Disorders](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-25-053.html){target="_blank"}
* Supports Small Business Technology Transfer (STTR) or Small Business Innovation Research (SBIR) grant applications proposing research projects directed towards commercialization to harness artificial intelligence (AI), including machine learning (ML), tools, and polypharmacology to identify pharmacotherapeutics with lower toxicity and higher efficacy to prevent or treat substance use disorders (SUDs).
* Deadline: June 25, 2024 (LOI), July 25, 2024
* Award: [R41/42](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-25-053.html){target="_blank"}, $400K (total) for one year (Phase 1) and $3M (total) over three years (Phase II); [R43/44](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-25-054.html){target="_blank"}, $400K (total) for one year (Phase 1) and $3M (total) over three years (Phase II)

### [Pilot Projects Enhancing Utility and Usage of Common Fund Data Sets](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-24-006.html){target="_blank"}
* Supports demonstration and enhancing the utility of selected Common Fund (https://commonfund.nih.gov/) data sets, including generating hypotheses and catalyzing discoveries
* Deadline: June 27, 2024
* Award: R03; $200K for up to one year

### [Leveraging Extant Data to Understand Developmental Trajectories of Late Talking Children](https://grants.nih.gov/grants/guide/pa-files/PAR-24-045.html){target="_blank"}
* Supports furthering understanding of the developmental trajectories of late talking children by leveraging existing data and creating open and shared data resources to aid in identifying patterns and predictors of developmental outcomes in late talking children, and exploring potential underlying mechanisms, risk factors, and sequelae. 
* Deadline: July 19, 2024, November 19, 2024
* Award: R21, $275K for up to two years

### [Early-stage Biomedical Data Repositories and Knowledgebases](https://grants.nih.gov/grants/guide/pa-files/PAR-23-236.html){target="_blank"}
* Supports the development of early-stage or new data repositories and knowledgebases that could be valuable for the biomedical research community. 
* Deadline: July 27, 2024 (LOI), September 25, 2024 (Proposal) and November 26, 2024 (LOI), January 25, 2025 (Proposal); annually through January 2026 (LOI due 60 days prior)
* Award: R24, $350K/year (direct) for durations up to 4 years

### [Examining the Impact of Artificial Intelligence (AI) on Healthcare Safety](https://grants.nih.gov/grants/guide/notice-files/NOT-HS-24-014.html){target="_blank"}
* Supports healthcare safety by determining (1) whether and how certain breakthrough uses of Artificial Intelligence (AI) systems can affect patient safety; and (2) how AI systems can be safely implemented and used. AI has the potential to improve the safety, effectiveness, efficiency, accessibility, and affordability of healthcare. 
* Deadline: Estimated to be Fall 2024
* Award: R18; Additional details coming wtih announcement

### [Secondary Analysis of Existing Datasets in Heart, Lung, and Blood Diseases and Sleep Disorders](https://grants.nih.gov/grants/guide/pa-files/PAR-23-036.html){target="_blank"}
* Supports secondary analyses using existing human datasets in areas relevant to the National Heart, Lung, Blood Diseases and Sleep Disorders Institute (NHLBI) scientific mission.
* Deadline: October 28, 2024; recurring in February and October through 2025
* Award: R21, $75K/year (direct) for durations up to two years

### [Education Activities for Responsible Analyses of Complex, Large-Scale Data](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-25-039.html){target="_blank"}
* Supports training and educational activities for responsible analyses of complex large-scale data involving brain, behavioral, genomic, and socioenvironmental data that complement and/or enhance the training of a workforce to meet the nation's biomedical, behavioral, and clinical research needs.
* Deadline: November 18, 2024 (LOI), December 18, 2024 (Proposal)
* Award: R25, $300K/year (direct) for durations up to three years

### [Research on Bioethical Issues Related to Bionic and Robotic Device Development and Translation](https://grants.nih.gov/grants/guide/rfa-files/RFA-EB-23-005.html){target="_blank"}
* Supports greater integration of bioethics within research and develop a robust bioethics research evidentiary base to inform policy and program decision-making.
* Deadline: January 21, 2025
* Award: R21, $275K direct for durations up to two years



## Other Activities
### [Systems Biology Data Platform (SysBio) Leveraging the Accelerating Medicines Partnership (AMP)](https://commonfund.nih.gov/sites/default/files/Research-Opportunity-Announcement-OTA-24-008-SysBio-updated-20240311_508.pdf){target="_blank"}
* Supports development of a platform that provides a single access point for querying data across the different tissues and conditions studied in the participating AMP projects.
* Deadline: May 15, 2024 (Proposal)
* Award: Negotiations to begin around June 12, 2024.
<!-- * Informational Webinar on March 18, 2024, 1:00-2:00pm MT. [Learn more and register here.](https://commonfund.nih.gov/venture/sysbio/faqs){target="_blank"} -->


### [Advancing Health Research through Ethical, Multimodal AI](https://datascience.nih.gov/sites/default/files/MAI-Solicitation-outline.pdf){target="_blank"}
* Supports ethically focused and data-driven multimodal AI approaches to more closely model, interpret, and predict complex biological, behavioural, and health systems and enhance our understanding of health and the ability to detect and treat human diseases. 
* Deadline: April 29, 2024 (LOI - optional), May 16, 2024 (Proposal)
* Award: OTA, $1-2M for durations of two years
* Informational Webinar on April 19, 2024 at 12pm MT, more information can be found [here](https://datascience.nih.gov/artificial-intelligence/MultimodalAI){target="_blank"}!

### [NHLBI TOPMed: Omics Phenotypes of Heart, Lung, and Blood Disorders](https://grants.nih.gov/grants/guide/pa-files/PAR-22-194.html){target="_blank"}
* Supports use of NHLBI-funded TransOmics for Precision Medicine (TOPMed) program to generate a large volume of integrated genetic and multi-omics data to facilitate discovery of the molecular mechanisms of Heart, Lung, Blood, and Sleep (HLBS) disorders. 
* Deadline: September 17, 2024 (LOI), October 17, 2024 (Proposal)
* Award: X01, access to data resource for up to three years

### [Diagnostic Centers of Excellence](https://grants.nih.gov/grants/guide/pa-files/PAR-23-171.html){target="_blank"}
* Supports access to resources provided by the Data Management Coordinating Center for Diagnostic Centers of Excellence (RFA-NS-22-051), as part of the next phase of the Undiagnosed Diseases Network. 
* Deadline: April 15, 2025 (LOI), May 15, 2025 (Proposal)
* Award: X01, access to data resource for up to three to five years




## Notices of Special Interest and Requests for Information
<!-- * [](https://grants.nih.gov/grants/guide/notice-files/NOT-CA-24-002.html){target="_blank"} expires -->
<!--* [](){target="_blank"} -->

* [**Request for Information** Proposed Use of Common Data Elements (CDEs) for NIH-Funded Clinical Research and Trials](https://datascience.nih.gov/cde-rfi){target="_blank"} expires May 7, 2024.
* [Harnessing Big Data to Halt HIV](https://grants.nih.gov/grants/guide/notice-files/NOT-AI-21-054.html){target="_blank"} expires May 8, 2024.
* [Maximizing the Scientific Value of Secondary Analyses of Existing Cohorts and Datasets in Order to Address Research Gaps and Foster Additional Opportunities in Aging Research](https://grants.nih.gov/grants/guide/notice-files/NOT-AG-23-020.html){target="_blank"} expires May 8, 2024.
* [**Request for Information** Data Management, Sharing, and Secondary Data Use Challenges and Opportunities](https://grants.nih.gov/grants/guide/notice-files/NOT-AG-24-013.html){target="_blank"}, expires May 31, 2024.
* [Advance Data Science Approaches Through Secondary Data Analysis to Reveal Scientific Insights of COVID-19 Testing Technologies (R21)](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-040.html){target="_blank"} extended to July 16, 2024.
* [Clinical and Translational Science Award (CTSA) Program: Collaborative and Innovative Acceleration Award (UG3/UH3) (Clinical Trial Optional) for Advancing Recruitment through Trial Innovation Network (AR-TIN)](https://grants.nih.gov/grants/guide/notice-files/NOT-TR-23-026.html){target="_blank"} expires October 18, 2024.
* [High-Priority Interest to Enhance Data Science Research Training in Addiction Research](https://grants.nih.gov/grants/guide/notice-files/NOT-DA-21-013.html){target="_blank"} expires December 9, 2024.
* [IDEA2Health: Innovative Data Evaluation and Analysis to Health](https://grants.nih.gov/grants/guide/notice-files/NOT-HL-22-001.html){target="_blank"} expires January 8, 2025.
* [Validation of Digital Health and Artificial Intelligence/Machine Learning Tools for Improved Assessment in Biomedical and Behavioral Research](https://grants.nih.gov/grants/guide/notice-files/NOT-CA-24-031.html){target="_blank"} expires July 6, 2025.
* [Advance Data Science Approaches Through Secondary Data Analysis to Reveal Scientific Insights of COVID-19 Testing Technologies (R21)](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-24-026.html){target="_blank"}, expires July 16, 2024.
* [Competitive Revision Supplements to Existing T32 Programs to Include Institutional Research Training in Data Science for Infectious and Immune Mediated Diseases](https://grants.nih.gov/grants/guide/notice-files/NOT-AI-24-012.html){target="_blank"}, expired January 8, 2025.
* [Leveraging Data Science to Bring Actionable Insights for Substance Use Prevention and Treatment](https://grants.nih.gov/grants/guide/notice-files/NOT-DA-23-006.html){target="_blank"} expires September 8, 2025.
* [Development and Implementation of Clinical Informatics Tools to Enhance Patients Use of Genomic Information](https://grants.nih.gov/grants/guide/notice-files/NOT-HG-22-011.html){target="_blank"} expires September 25, 2025.
* [HEAL Initiative: Leveraging Inpatient Medical or Surgical Hospitalizations to Improve Outcomes for People Who Use Drugs](https://grants.nih.gov/grants/guide/notice-files/NOT-DA-24-011.html){target="_blank"} expires November 13, 2025.
* [Optimization of Data Storage and Utilization for the Sequence Read Archive (SRA)](https://grants.nih.gov/grants/guide/notice-files/NOT-GM-23-015.html){target="_blank"} expires December 19, 2025.
* [Computational and Statistical Methods to Enhance Discovery from Health Data](https://grants.nih.gov/grants/guide/notice-files/NOT-LM-23-001.html){target="_blank"} expires January 8, 2026.
* [Explainable Artificial Intelligence for Decoding and Modulating Neural Circuit Activity Linked to Behavior](https://grants.nih.gov/grants/guide/notice-files/NOT-MH-23-110.html){target="_blank"} expires February 6, 2026.
* [Applications of Data Science in Translational Dental, Oral, and Craniofacial Research](https://grants.nih.gov/grants/guide/notice-files/NOT-DE-23-002.html){target="_blank"} expires May 8, 2026.
* [Secondary Analyses of Existing Alcohol Research Data](https://grants.nih.gov/grants/guide/notice-files/NOT-AA-23-011.html){target="_blank"} expires September 6, 2026.
* [Promoting Data Reuse for Health Research](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-24-096.html){taret="_blank"} expires November 4, 2026. 

## Funding Opportunity Resources
* See the [full listing of *All of Us* funding opportunities](https://allofus.nih.gov/funding-and-program-partners/funding-opportunities?utm_medium=email&utm_source=mailchimp&utm_campaign=researcher_news&utm_medium=email&utm_source=mailchimp&utm_campaign=researcher_news){target="_blank"}.

* [NIH Office for Data Science Strategy](https://datascience.nih.gov/research-and-training-funding){target="_blank"} list of funding opportunities.

Updated April 24, 2024.