---
title: "Archived Funding"
format: html
---

# NIH Funding Opportunities
## Cooperative Agreement (U) Grants
### [HEAL INITIATIVE: Development and validation of remote or patient wearable device derived objective biosignatures or functional assessments to monitor pain for use as endpoints in clinical trials](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-24-023.html){target="_blank"}
* Supports the discovery, development, and validation of real-world digital endpoints derived from data generated by existing remote or wearable devices. These endpoints will be used for monitoring the experience of pain, its progression, response to interventions, and impact on quality of life.
* Deadline: December 30, 2023 (LOI), January 30, 2024 (Proposal); recurring on October 4, 2024
* Award: UH3/UG3, UG3 - $500K/year (direct) for durations up to two years, UH3 - $1.5M/year (direct) for durations up to three years

### [Partnerships With Common Fund Data Ecosystem Resources](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-23-013.html){target="_blank"}
* Supports projects that involve collaboration with multiple CF Data Coordinating Centers (DCCs) to combine discovery and/or translational approaches with work that will enhance reusability of Common Fund data and contribute knowledge to the Common Fund Data Ecosystem.  
* Deadline: December 4, 2023 (LOI due 1 month prior if budget is >$500K/year, direct)
* Award: U24, budget must align with the project scope for durations up to three years

### [Consortium Organization and Data Collaboration Center (CODCC) for the Human Virome Project (HVP)](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-23-016.html){target="_blank"}
* Supports the HVP CODCC to serve as an organizational hub to provide support for administrative activities, promotion of research protocols and tool development, and assist data and biospecimen collection and harmonization. The CODCC will create and maintain a program data portal that will be an interactive dashboard and repository with visualization and search capabilities. 
* Deadline: November 29, 2023 (LOI due 1 month prior)
* Award: U24, $1.875M/year (direct) for duration up to five years

### [Early-Stage Development of Informatics Technologies for Cancer Research and Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-23-015.html){target="_blank"}
* Supports the development of enabling informatics technologies to improve the acquisition, management, analysis, and dissemination of data and knowledge across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and/or cancer health disparities. 
* Deadline: November 17, 2023 (LOI due 1 month prior)
* Award: U01, $300K/year (direct) for durations of three years

### [Network of Genomics-Enabled Learning Health Systems (gLHS) – Coordinating Center](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-042.html){target="_blank"}
* Supports a network of genomic-enabled learning health systems (gLHS) to identify and improve approaches for clinical integration of genomic information in a virtuous cycle of implementation, assessment, refinement, and reimplementation. Specifically, this initiative would support a coordinating center (CC) for 4-6 established or emerging gLHS clinical sites to share their genomic medicine implementation practices and identify those most suitable for cross-network implementation. 
* Deadline: November 7, 2023 (LOI due 1 month prior)
* Award: U01, $1.6M/year for durations of five years

### [Network of Genomic-Enabled Learning Health Systems (gLHS) – Clinical Sites](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-041.html){target="_blank"}
* Supports a network of genomic-enabled learning health systems (gLHS) to identify and improve approaches for clinical integration of genomic information in a virtuous cycle of implementation, assessment, refinement, and reimplementation. Specifically, this initiative would support  4-6 established or emerging gLHS clinical sites to share their genomic medicine implementation practices and identify those most suitable for cross-network implementation. 
* Deadline: November 7, 2023 (LOI due 1 month prior)
* Award: U01, budget must align with the project scope ($750K/year) for durations of five years

### [Diagnostic Centers of Excellence for the Undiagnosed Diseases Network](https://grants.nih.gov/grants/guide/pa-files/PAR-23-289.html){target="_blank"}
* Supports clinical sites that will provide expert diagnostic services for undiagnosed diseases across the nation.  
* Deadline: November 3, 2023 (LOI due 1 month prior)
* Award: U01, $500K (direct) 

### [Quantifying the Impact of Environmental Toxicants on Alzheimer's Disease (AD) and AD-Related Dementias (ADRD) Risk in Cohort Studies](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-022.html){target="_blank"}
* Supports research focused on major toxicants observed to be associated with elevated Alzheimer's Disease (AD) and AD-related dementias (ADRD) risk, and health disparities in AD/ADRD-related pathologic and clinical outcomes.
* Deadline: October 23, 2023 (LOI due 1 month prior)
* Award: U01, $1.5M/year (direct) for durations up to five years

### [Integration of Novel Measures for Improved Classification of Type 2 Diabetes](https://grants.nih.gov/grants/guide/rfa-files/rfa-dk-23-019.html){target="_blank"}
* Supports a consortium to bring together investigative teams for integration of multiple data types, including markers of organ or tissue function, into analysis approaches for stratifying individuals with type 2 diabetes (T2D) and developing more precise definitions of disease. 
* Deadline: October 26, 2023 (LOI due 1 month prior)
* Award: U01, $500K/year (direct) for durations up to five years

### [Integration of Novel Measures for Improved Classification of Type 2 Diabetes – Biostatistics Research Center](https://grants.nih.gov/grants/guide/rfa-files/rfa-dk-23-020.html){target="_blank"}
* Supports a Biostatistics Research Center to participate in a consortium aimed at improving understanding of heterogeneity of type 2 diabetes (T2D).
* Deadline: October 26, 2023 (LOI due 1 month prior)
* Award: U01, $1M/year (direct) for durations up to five years

### [Center for ELSI Resources and Analysis](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-027.html){target="_blank"}
* Supports the renewal of the Center for ELSI Resources and Analysis (CERA), that will: 1) provide ELSI researchers with an online platform to share ELSI research products; 2) curate and synthesize ELSI research; and 3) facilitate new research collaborations and uptake of ELSI research. 
* Deadline: October 26, 2023 (LOI due 1 month prior)
* Award: U01, $1.5M/year (direct) for durations up to five years (max $6M)

### [Research Coordinating Center on the Exposome and Alzheimer's Disease (AD) and AD-Related Dementias (ADRD): Elucidating the Role of Social and Behavioral Determinants of Health in AD/ADRD Etiology and Disparities](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-011.html){target="_blank"}
* Supports the establishment of a national coordinating center that will serve as a centralized hub for accessing, harmonizing, linking, and sharing environmental contextual data and individual exposure data with NIA/NIH-funded projects. 
* Deadline: October 27, 2023 (LOI due August 27, 2023)
* Award: U24, $5M/year for durations of five years

### [Informatics Tools for the Pangenome](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-026.html){target="_blank"}
* Supports the development of informatics tools to facilitate uptake and scientific use of the human pangenome reference being developed and maintained by the NHGRI Human Genome Reference Program (HGRP).
* Deadline: November 1, 2023 or March 3, 2025 (LOI due 1 month prior)
* Award: U01, $400L/year (direct) for durations up to three years

### [Broadening Opportunities for Computational Genomics and Data Science Education](https://grants.nih.gov/grants/guide/rfa-files/RFA-HG-23-002.html){target="_blank"}
* Supports faculty members at institutions with a mission to serve historically underrepresented populations in biomedical research to develop undergraduate and master’s degree-level educational content in computational genomics, data science, or a combination of these topics.
* Deadline: October 10, 2023 (LOI due 1 month prior), June 10, 2024
* Award: UE5, $150K/year (direct) for three years

### [Using Secondary Data Analysis to Determine Whether Preventive Interventions Implemented Earlier in Life Reduce Suicide Risk](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-275.html){target="_blank"}
* Supports research that will integrate and harmonize existing large prevention trial data sets consisting of well-characterized participant-level data for interventions implemented earlier in life to examine whether they reduce risk for later suicide, including suicidal thoughts and behaviors — fatal and nonfatal (STB), and related external injuries (e.g., nonfatal SUD/OUD/accidents, and all-cause mortality (e.g., National Death Index)). 
* Deadline: October 10, 2023 (LOI due 1 month prior)
* Award: U01, budget must align with the project scope ($3M/year), for durations up to four years

### [Development of Software for Data Science in Infectious and Immune-Mediated Diseases Research](https://grants.nih.gov/grants/guide/rfa-files/RFA-AI-23-038.html){target="_blank"}
* Supports the development of software to improve the acquisition, management, analysis, visualization, and dissemination of data and knowledge for data science research on infectious and immune-mediated diseases (IID). 
* Deadline: October 11, 2023 (LOI due 1 month prior)
* Award: U01, $300K/year (direct) for durations of three years

### [Precision Mental Health: Develop Tools to Inform Treatment Selection in Depression](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-24-120.html){target="_blank"}
* Supports creation of a pipeline to accelerate the development and early validation of predictive tools and/or biomarkers to inform individual-level treatment selection among two or more existing therapeutics for depression. 
* Deadline: October 18, 2023 (LOI due 1 month prior); October 18, 2024
* Award: UG3/UH3, $500K/year (direct) for one to two years (UG3), followed by $1.5M/year (direct) for a total duration up to five years

### [Data Analysis and Coordination Center for the PsychENCODE Consortium](https://grants.nih.gov/grants/guide/pa-files/PAR-23-234.html){target="_blank"}
* Supports a Data Analysis and Coordination Center for PsychENCODE, a NIMH consortium for the discovery and characterization of human-specific non-coding functional genomic elements across brain regions, cell types, and developmental time periods and their role(s) in the molecular pathophysiology of psychiatric disorders.
* Deadline: August 24, 2023 (LOI due 1 month prior)
* Award: U24, budget must align with the project scope, for durations up to four years

### [Bioinformatics Resource Centers (BRCs) for Infectious Diseases](https://grants.nih.gov/grants/guide/rfa-files/RFA-AI-23-032.html){target="_blank"}
* Supports the Bioinformatics Resource Center (BRC) Program that will (1) create and manage integrated knowledgebases to accelerate basic and applied human infectious diseases research, (2) develop advanced innovative bioinformatics technologies for software and tools, (3) offer state-of-the-art bioinformatics expertise for investigators and (4) respond with cutting-edge bioinformatics in response to emerging needs, outbreaks, and public health emergencies.
* Deadline: August 25, 2023 (LOI due 1 month prior)
* Award: U24, $2.5M/year (direct) for one biological domain, $4.8M/year (direct) for two biological domains, for durations up to five years

### [Alzheimer's Disease (AD) and AD-Related Dementias (ADRD) Real-World Data Platform](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-009.html){target="_blank"}
* Supports the transformation of the AD/ADRD research enterprise by serving as a central hub of research access that seeks to: 1) improve applicability and generalizability of findings through larger datasets that include more diverse populations; 2) capture more complete information through linking a variety of data sources; 3) increase the speed at which scientific questions can be answered; and 4) improve researchers’ ability to answer questions that cannot be feasibly or readily answered via clinical trial.
* Deadline: July 31, 2023 (LOI due 1 month prior)
* Award: U54, $52M/year for durations up to six years

### [BRAIN Initiative: Brain Behavior Quantification and Synchronization – Data Coordination and Artificial Intelligence Center](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-130.html)
* Data Coordination and Artificial Intelligence Center (DCAIC) for the Brain Behavior Quantification and Synchronization (BBQS) Consortium of the BRAIN Initiative. The DCAIC will serve as the organizational hub for BBQS data management and sharing. 
* Deadline: June 14, 2023
* Award: U24, $2M/year for durations up to five years

### [Integration and Coordination Center for the Common Fund Data Ecosystem](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-23-002.html)
* Supports an Integration and Coordination Center (ICC) for the Common Fund Data Ecosystem (CFDE) that will help to build internal cohesion within the program
* Deadline: June 28, 2023 (LOI due 1 month prior)
* Award: U54, budget must align with the project scope, for durations up to five years

### [Individually Measured Phenotypes to Advance Computational Translation in Mental Health (IMPACT-MH)](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-105.html)
* Supports research that will use behavioral measures and computational methods to define novel clinical signatures that can be used for individual-level prediction and clinical decision making in mental disorders. 
* Deadline: June 14, 2023 (LOI due 1 month prior)
* Award: U01, $2.5M/year (direct) for durations up to five years

### [Individually Measured Phenotypes to Advance Computational Translation in Mental Health (IMPACT-MH): Data Coordinating Center](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-106.html)
* Supports the work of U01 research projects funded under the Individually Measured Phenotypes to Advance Computational Translation in Mental Health (IMPACT-MH) initiative described in the companion announcement [RFA-MH-23-105](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-23-105.html). 
* Deadline: June 14, 2023 (LOI due 1 month prior)
* Award: U24, $1M/year (direct) for durations up to five years

## Program and Center (P) Grants
### [Exploratory Grants for Climate Change and Health Research Center Development](https://grants.nih.gov/grants/guide/rfa-files/RFA-ES-23-007.html){target="_blank"}
* Supports the development of a transdisciplinary research environment to sustain a program of fundamental and applied research to examine the impacts of climate change on health and to develop action-oriented solutions to protect the health of individuals, communities, and nations from the hazards posed by climate change.
* Deadline: November 7, 2023 (LOI due 1 month prior)
* Award: P20, $850K/year (direct) for durations up to three years
* [Webinar on August 17 at 11:00 am MT](https://nih.zoomgov.com/webinar/register/WN_PYfwfWOnT_iGcywfUWTO7Q)

### [Developmental AIDS Research Centers on Mental Health and HIV/AIDS](https://grants.nih.gov/grants/guide/pa-files/PAR-20-307.html){target="_blank"}
* Supports Developmental HIV/AIDS Research Centers (D-ARC) intended to provide infrastructure support that facilitates the development of high impact science in HIV/AIDS and mental health that is relevant to the NIMH mission. 
* Pursuit of innovative data science approaches to promote HIV treatment and prevention delivery advances. This may include methods such as artificial intelligence and predictive analytics applied to large data sets that include electronic medical records, pharmacy claims data, and medical insurance data, as well as the integration of digital technology data (e.g., cellphones or other sensors) with other datasets to improve service delivery and impact.
* Deadline: August 25, 2023 (LOI due 1 month prior)
* Award: P30, $750K/year for durations up to four years

### [NIMH AIDS Research Center on Mental Health and HIV/AIDS](https://grants.nih.gov/grants/guide/pa-files/PAR-20-308.html){target="_blank"}
* Supports HIV/AIDS Research Centers (ARC) intended to provide infrastructure support that facilitates the development of high impact science in HIV/AIDS and mental health that is relevant to the NIMH mission. 
* Pursuit of innovative data science approaches to promote HIV treatment and prevention delivery advances. This may include methods such as artificial intelligence and predictive analytics applied to large data sets that include electronic medical records, pharmacy claims data, and medical insurance data, as well as the integration of digital technology data (e.g., cellphones or other sensors) with other datasets to improve service delivery and impact.
* Deadline: August 25, 2023 (LOI due 1 month prior)
* Award: P30, $1.5M/year for durations up to five years


## Career Development (F/K) Grants
### [Maximizing the Scientific Value of Data Generated by the Environmental Influences on Child Health Outcomes (ECHO) Program: Ruth L. Kirschstein National Research Service Award (NRSA) Individual Postdoctoral Fellowship](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-23-019.html){target="_blank"}
* Supports advanced research and training in high-priority areas of child health by stimulating the use of Environmental Influences on Child Health Outcomes ([ECHO](https://www.nih.gov/research-training/environmental-influences-child-health-outcomes-echo-program){target="_blank"}) Cohort data by postdoctoral fellows from  relevant scientific communities. 
* Deadline: November 1, 2023
* Award: F32, three years of support

### [NHLBI Trans-Omics for Precision Medicine (TOPMed) Fellowship](https://topmed.nhlbi.nih.gov/2023-topmed-fellowship){target="_blank"}
* Supports the career advancement and/or transition of participants to the next steps in their scientific careers and to develop a cadre of diverse scientists capable of leading genomic data science research in the areas relevant to heart, lung, blood, and sleep disorders.
* Deadline: July 31, 2023
* Award: Salary and travel support for one year

### [INCLUDE (INvestigation of Co-occurring conditions across the Lifespan to Understand Down syndromE) Predoctoral to Postdoctoral Fellow Transition Award](https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-23-016.html){target="_blank"}
* Supports exceptional graduate students from a broad variety of  research fields to pursue postdoctoral training focused on Down syndrome related research.
* Deadline: July 1, 2023
* Award: F99/K00, covers stipends, tuition, fees, and institutional allowance for durations up to six years (F99 for two years, K00 for four years).

## Research Grants - R01 Activities

### [Short Courses to Promote the Broad and Rigorous Use of Common Fund Data](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-23-014.html){target="_blank"}
* Supports research education activities in the mission areas of the NIH.  The overarching goal of this R25 program is to support educational activities that complement and/or enhance the training of a workforce to meet the nation’s biomedical, behavioral and clinical research needs.
* Deadline: January 14, 2024 (LOI), February 14, 2024 (Proposal)
* Award: R25, $350K/year (direct) for durations of three years

### [Computational Approaches to Curation at Scale for Biomedical Research Assets](https://grants.nih.gov/grants/guide/pa-files/PAR-20-304.html){target="_blank"}
* Supports the availability of and access to secure, complete data sets and computational models that can serve as the basis of transformative biomedical discoveries by improving the speed and scope of the curation processes.
* Deadline: January 6, 2024 (LOI), February 5, 2024 (Proposal)
* Award: R01, $250K/year (direct) for durations up to four years

### [Accelerating the Pace of Drug Abuse Research Using Existing Data](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-22-037.html){target="_blank"}
* Supports the  analysis of the Adolescent Brain Cognitive Development (ABCD) dataset to increase knowledge of adolescent health and development. 
* Deadline: November 15, 2023 (LOI due 1 month prior), annually in March, August, November through 2024
* Award: R01, approximately $400-650K/year for durations up to five years ([R21](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-22-038.html){target="_blank"} also available)

### [Computational Approaches for Validating Dimensional Constructs of Relevance to Psychopathology](https://grants.nih.gov/grants/guide/pa-files/PAR-21-263.html){target="_blank"}
* Supports research projects that will use computational approaches to test the validity of dimensional constructs in the NIMH [Research Domain Criteria (RDoC) matrix](https://www.nimh.nih.gov/research-priorities/rdoc/index.shtml){target="_blank"} (or similar constructs based on comparable criteria). 
* Deadline: November 1, 2023 (LOI due 1 month prior)
* Award: R01, $500K/year (direct) for durations up to five years

### [Translational Bioinformatics Approaches to Advance Drug Repositioning and Combination Therapy Development for Alzheimer’s Disease](https://grants.nih.gov/grants/guide/pa-files/PAR-20-156.html){target="_blank"}
* Supports data-driven drug repositioning and combination therapy for Alzheimer's disease and Alzheimer's disease-related dementias (AD/ADRD) by developing computational methods and data resources and/or integrating computational approaches with proof-of-concept efficacy studies in cell-based models, animal models, and/or humans.
* Deadline: September 8, 2023
* Award: R01, budget must align with the project scope, for durations of up to five years

### [Enhancing Use of Harmonized Cognitive Assessment Protocol Data](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-032.html){target="_blank"}
* Supports  analyses of HCAP data from the U.S. or from another country where HCAP data is available, or cross-national analyses of HCAP data. This research will help further our understanding of how different behavioral, social, cultural, environmental, and institutional factors affect the trajectory of cognitive aging and AD/ADRD and the experience of living with or managing AD/ADRD in different national or regional contexts.
* Deadline: October 2, 2023 (LOI due 1 month prior)
* Award: R01, $500K/year (direct) for durations up to five years

### [Leveraging Big Data Science to Elucidate the Mechanisms of HIV Activity and Interaction with Substance Use Disorder](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-24-008.html){target="_blank"}
* Supports research using data science and computational approaches to generate new insights into mechanisms and consequences of the interaction of HIV and addictive drugs. 
* Deadline: August 10, 2023 (LOI due 1 month prior)
* Award: R01, $350K (direct) for durations up to five years ([R21](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-24-009.html){target="_blank"} also available)

### [Strategies for Responsibly Reporting Back Environmental Health and Non-Genomic Research Results](https://grants.nih.gov/grants/guide/rfa-files/RFA-ES-23-006.html){target="_blank"}
* Supports projects that will identify, develop and/or adapt, as well as test strategies for responsibly reporting back environmental health, non-genomic research, and gene-environment interaction (GxE) results to research participants and/or key partners (for example, health care professionals, IRBs, and policy makers)
* Deadline: June 15, 2023 (LOI due 1 month prior)
* Award: R01, $250K/year for durations up to four years

## Research Grants - Other Activities
### [Education Activities for Responsible Analyses of Complex, Large-Scale Data](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-24-027.html){target="_blank"}
* Supports research education activities in the mission areas of the NIH. The overarching goal of this NIDA R25 program is to support training and educational activities for responsible analyses of complex large-scale data involving brain, behavioral, genomic, and socioenvironmental data that complement and/or enhance the training of a workforce to meet the nation's biomedical, behavioral, and clinical research needs.
* Deadline: January 8, 2024 (LOI), February 8, 2024 (Full Proposal)
* Award: R25, $300K/year (direct) for durations up to three years

### [Precision HIV Health: Integrating Data and Implementation Science to Accelerate HIV Prevention and Treatment](https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-24-100.html){target="_blank"}
* Supports participatory data science and implementation science research to accelerate the implementation of more targeted and sustainable HIV interventions with the goals of (1) using data science methods to model complex systems, including social and structural determinants of health, to identify more targeted HIV prevention, treatment, and care interventions and implementation strategies; (2) using novel measurement approaches and modern statistical methods to evaluate the implementation of data-driven discoveries; (3) integrating meaningful engagement of community and implementing partners at every stage of the research.
* Deadline: November 22, 2023 (LOI due 1 month prior)
* Award: R21/R33, $275K (direct) for durations up to two years for R21, $375K (direct) for durations up to three years for R33

### [Development of Innovative Informatics Methods and Algorithms for Cancer Research and Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-23-014.html){target="_blank"}
* Supports exploratory/developmental research grant applications (R21) for innovative informatics methods and algorithms to improve the acquisition, analysis, visualization, or interpretation of data across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and/or cancer health disparities. 
* Deadline: November 17, 2023
* Award: R21, $275K (direct) for durations up to two years

### [Pilot Projects Enhancing Utility and Usage of Common Fund Data Sets](https://grants.nih.gov/grants/guide/rfa-files/RFA-RM-23-015.html){target="_blank"}
* Supports the demonstration and enhancement of the utility of selected [Common Fund](https://commonfund.nih.gov/){target="_blank"} data sets, including generating hypotheses and catalyzing discoveries.
* Deadline: November 17, 2023
* Award: R03, $200K (direct) for one year

### [Analysis of data in the COVID-19 Neuro Databank-Biobank](https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-24-025.html){target="_blank}
* Supports applications that aggregate and analyze existing data in the COVID-19 Neuro Databank-Biobank (NeuroCOVID Project).
* Deadline: November 8, 2023 (LOI due 30 days prior)
* Award: R03, $50K/year (direct) for durations up to two years

### [Leveraging Social Networks to Promote Widespread Individual Behavior Change](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-026.html){target="_blank"}
* Supports the planning activities necessary to develop social network interventions to promote health across the lifespan, especially in populations in which they are currently largely underdeveloped and untested (such as populations in mid- and late-life). 
* Deadline: November 3, 2023 (LOI due 1 month prior)
* Award: R34, $450K (direct) for durations up to three years

### [HEAL Initiative: Toward Developing Quantitative Imaging and Other Relevant Biomarkers of Myofascial Tissues for Clinical Pain Management](https://grants.nih.gov/grants/guide/rfa-files/RFA-AT-24-003.html){target="_blank"}
* Supports the development of innovative methods for quantitative evaluation of  myofascial tissues for pain management involving research participants using a two-phase grant funding mechanism.
* Deadline: October 18, 2023 (LOI due 1 month prior)
* Award: R61/R33, $500K/year (direct) for durations up to two years for R61, $700K/year (direct) for durations up to three years for R33

### [Research Resource for Systematic Reviews of Complementary and Integrative Health](https://grants.nih.gov/grants/guide/rfa-files/RFA-AT-24-005.html){target="_blank"}
* Supports a research resource that will continue to build, grow and maintain a database of clinical trials of complementary and integrative health interventions, that can be used to conduct systematic reviews to inform the public, practitioners, and policy makers. The research team will need to describe the features of the database, and whether it is building upon or converting an existing database, and how it will be maintained and kept current during the award period.
* Deadline: August 31, 2023
* Award: R24, $400K/year (direct) for durations up to five years

### [Team Science Approaches Integrating Experimental and Computational Brain Aging Models](https://grants.nih.gov/grants/guide/rfa-files/RFA-AG-24-018.html){target="_blank"}
* Supports establishing new, or significantly expanding existing, interdisciplinary collaborations involving both experimental and computational researchers to simultaneously address a targeted research question in brain aging and Alzheimer's disease (AD), including AD-related dementias (ADRD).
* Deadline: September 22, 2023 (LOI due 1 month prior)
* Award: R21/R33, $275K/year (direct) for R21 and $500K/year (direct) for R33 for durations up to five years (two years for R21, three years for R33) 

### [Emergency Award: Novel Insights through Cross-Site Analyses of Existing RADx-UP Data](https://grants.nih.gov/grants/guide/rfa-files/rfa-od-23-050.html){target="_blank"}
* Supports analyses of existing RADx-UP data by proposing novel questions related to SARS-CoV-2 testing and health disparities. These projects will explore important questions focused on COVID-19 testing access and uptake, factors affecting testing and related COVID-19 outcomes, and meta-fanalyses of specific COVID-19 response and intervention approaches within and across populations.
* Deadline: July 3, 2023 (LOI due one month prior)
* Award: R21, $275K/year (direct) for durations of two years.


## Other Activities
### [NIDA REI: Training a Diverse Data Science Workforce for Addiction Research](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-24-025.html){target="_blank"}
* Supports research education activities in the mission areas of the NIH.  The overarching goal of this R25 program is to support educational activities that complement and/or enhance the training of a workforce to meet the nation’s biomedical, behavioral and clinical research needs.
* Deadline: December 24, 2023 (LOI), January 24, 2024 (Proposal)
* Award: R25, $125K/year (direct) for durations up to five years ([R15 Opportunity](https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-24-026.html){target="_blank"} also available.)

### [Data and Technology Advancement (DATA) National Service Scholar Program: Data Scientists Advancing Biomedical Research](https://datascience.nih.gov/data-scholars-2023){target="_blank"}
* The National Institutes of Health (NIH) Office of Data Science Strategy (ODSS) Data and Technology Advancement (DATA) National Service Scholar Program is seeking experienced data and computer scientists and engineers to tackle challenging biomedical data problems with the potential for substantial public health impact
* Application Deadline: EXTENDED to May 31, 2023
* Award: Remote position for one to two years

### [Artificial Intelligence/Machine Learning Consortium to Advance Health Equity and Researcher Diversity (AIM-AHEAD)](https://www.aim-ahead.net/call-for-proposals-year-2/){target="_blank"}
* [Consortium Development Projects to Advance Health Equity](https://www.aim-ahead.net/call-for-proposals-year-2/consortium-development-projects/){target="_blank"}
	+ Supports multidisciplinary research projects that use AI/ML and develop novel algorithms and approaches that address health disparities and inequities and have the potential to significantly impact healthcare access and health outcomes for populations that experience health disparities.
	+ Deadline: June 20, 2023 (LOI due May 10, 2023)
	+ Award: $500K-1M for durations up to two years

## Notices of Special Interest and Requests for Information
* [**Request for Information** Best Practices for Sharing NIH Supported Research Software](https://datascience.nih.gov/rfi-software){target="_blank"} expires February 1, 2024.
* [**Request for Information** NCI Cancer Research Data Commons (CRDC) Artificial Intelligence (AI) use cases to inform an assessment of data readiness](https://grants.nih.gov/grants/guide/notice-files/NOT-CA-24-017.html){target="_blank"} due by December 31, 2023.
* [**Request for Information** Opportunities and Challenges for the Collection, Use, and Sharing of Real-World Data (RWD) including Electronic Health Records, for NIH Supported Biomedical and Behavioral Research](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-180.html){target="_blank"} due by December 14, 2023.
* [**Request for Information** Exploring the role of Generative AI in enhancing the use of Big Data in Heart, Lung, Blood, and Sleep (HLBS) research](https://grants.nih.gov/grants/guide/notice-files/NOT-HL-23-097.html){target="_blank"} due by December 5, 2023.
* [**Request for Information** NCI Cancer Research Data Commons (CRDC) Artificial Intelligence (AI) use cases to inform an assessment of data readiness](https://grants.nih.gov/grants/guide/notice-files/NOT-CA-24-002.html){target="_blank"} expires November 30, 2023. 
* [**Request for Information** National Institute of Dental and Craniofacial Research (NIDCR) Strategic Planning of Infrastructure and Resources for Data Science Research and Research Training](https://grants.nih.gov/grants/guide/notice-files/NOT-DE-23-008.html){target="_blank"} due by September 25, 2023.
* [NIDCR: Supporting Dental, Oral, and Craniofacial Research Using Bioinformatic, Computational, and Data Science Approaches](https://grants.nih.gov/grants/guide/notice-files/NOT-DE-20-006.html){target="_blank"} expires August 08, 2023.
* [**Request for Information** NIH Common Fund is Soliciting Ideas for NIH-wide Challenges and Opportunities](https://grants.nih.gov/grants/guide/notice-files/NOT-RM-23-013.html){target="_blank"} due by August 11, 2023.
* [**Request for Information** Catalyzing the Development and Use of Novel Alternative Methods to Advance Biomedical Research](https://osp.od.nih.gov/request-for-information-rfi-catalyzing-the-development-and-use-of-novel-alternative-methods-to-advance-biomedical-research/){target="_blank"} due by August 16, 2023.
* [**Request for Input** National Library of Medicine, National Center for Biotechnology Information Data Submission Survey](https://nlmenterprise.co1.qualtrics.com/jfe/form/SV_6fMaMvvU5IoQk5g){target="_blank"} expires July 31, 2023.
* [**Administrative Supplements** to Support Collaborations to Improve Data Interoperability/Re-use for Existing Type 2 Diabetes Relevant Data Sets](http://grants.nih.gov/grants/guide/notice-files/NOT-DK-23-022.html){target="_blank"} expires July 12,2023. 
* [Administrative Supplements to Support Collaborations to Improve the AI/ML-Readiness of NIH-Supported Data](https://grants.nih.gov/grants/guide/notice-files/not-od-23-082.html){target="_blank"} expires May 17, 2023.


# NSF Funding Opportunities
### [Cybersecurity Innovation for Cyberinfrastructure (CICI)](https://new.nsf.gov/funding/opportunities/cybersecurity-innovation-cyberinfrastructure-cici){target="_blank"}
*   Supports work that enables scientists and scientific discovery by improving the security, robustness, and trustworthiness of cyberinfrastructure.
    *   *Usable and Collaborative Security for Science (UCSS)*: Projects in this program area should support novel and/or applied security and usability research that facilitates scientific collaboration, encourages the adoption of security into the scientific workflow, and helps create a holistic, integrated security environment that spans the entire scientific cyberinfrastructure ecosystem.
    *   *Reference Scientific Security Datasets (RSSD)*: Projects in this program area should leverage instrumented cyberinfrastructure to capture metadata from scientific workflows and workloads as reference data artifacts that can help support reproducible security research, testing and evaluation.
    *   *Transition to Cyberinfrastructure Resilience (TCR)*: Projects in this program area should improve the robustness, trustworthiness, integrity, and/or resilience of scientific cyberinfrastructure through testing, evaluation, hardening, validation, and technology transition of novel cybersecurity research. The TCR area further encourages transition activities that advance the deployment and use of reproducibility in CI, workflows, and data.
*   Deadline: February 1, 2024
*   Award: \$600K *(UCSS and RSSD)* - \$1.2M *(TCR)* for durations up to three years

### [Safe Learning-Enabled Systems](https://new.nsf.gov/funding/opportunities/safe-learning-enabled-systems){target="_blank"}
*   Supports foundational research that leads to the design and implementation of learning-enabled systems in which safety is ensured with high levels of confidence.
    *   *Foundation* Projects
    *   *Synergy* Projects
*   Deadline: January 16, 2024
*   Award: *Foundation* \$800K for durations up to three years; *Synergy* \$1.5M for durations up to four years

### [Synthesis Center for Understanding Organismal Resilience](https://new.nsf.gov/funding/opportunities/synthesis-center-understanding-organismal){target="_blank"}
* Supports the establishment of a new Synthesis Center focused on organismal resilience and plasticity as well as training new generations of researchers in data-intensive, open, cross-disciplinary and collaborative science.
* Deadline: January 12, 2024 (Preliminary); July 15, 2024 (Full Proposal)
* Award: $20M over five years
<!-- * [UofU Townhall on May 24 at 4pm](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NXFrMzhpOWl2bHU5cnU5ajVxdDI0dWswcGMgY2Y0ZDA4OThhMjJiMmQxOTY5NzU1ZDRiYmU3NzA2M2U4MGVhNDgxMGEyNGEyYTI0ZWQ4NDAwM2IyMjU0NGY1NEBn&tmsrc=cf4d0898a22b2d1969755d4bbe77063e80ea4810a24a2a24ed84003b22544f54%40group.calendar.google.com){target="_blank"} -->

### [Ideas Lab: Personalized Engineering Learning (PEL)](https://new.nsf.gov/funding/opportunities/ideas-lab-personalized-engineering-learning-pel){target="_blank"}
* The goal of the Personalized Engineering Learning Ideas Lab is to extend engineering education research to enable advanced personalization in pedagogy and assessment in a K-12 or higher education context. The following broad areas have been identified as possible avenues to advance knowledge: personalized engineering education, multimodal sensing for personalized learning systems and team-based personalized learning.
* Deadline: November 29, 2023 (Preliminary Proposal); May 8, 2024 (Full Proposal)
* Award: Selected individuals will participate in an Ideas Lab and may be selected to submit a full proposal

### [Trailblazer Engineering Impact Award](https://new.nsf.gov/funding/opportunities/nsf-trailblazer-engineering-impact-award){target="_blank"}
* Supports individual engineers and scientists who propose novel research projects with the potential to innovatively and creatively address major societal challenges, advance US leadership, and catalyze the convergence of engineering and science domains.
* Deadline: Concept Outline due November 9, 2023; Full Proposal due February 15, 2024
* Award: $3M for durations up to three years

### [Campus Cyberinfrastructure (CC\*)](https://new.nsf.gov/funding/opportunities/campus-cyberinfrastructure-cc){target="_blank"}
* Supports coordinated campus-level networking and cyberinfrastructure improvements for science applications and distributed research projects.
  + Area (1) Data-Driven Networking Infrastructure for the Campus and Researcher;
  + Area (2) Regional Connectivity for Small Institutions of Higher Education;
  + Area (3) Network Integration and Applied Innovation;
  + Area (4) Campus Computing and the Computing Continuum;
  + Area (5) Regional Computing;
  + Area (6) Data Storage; and
  + Area (7) Planning Grants and CI-Research Alignment.
* Deadline: September 11, 2023
* Award: \$100K - \$1.2M depending on area for durations up to two years

### [Predictive Intelligence for Pandemic Prevention Phase II (PIPP Phase II Centers Program)](https://new.nsf.gov/funding/opportunities/predictive-intelligence-pandemic-prevention-phase){target="_blank"}
* Supports interdisciplinary team-based approaches to accelerate research and development activities in emerging infectious diseases and pandemics. The overall goal of the PIPP Phase II Centers program is to support research and development activities needed to transform society’s ability to forecast the likelihood of pandemic-scale events, detect outbreaks early, and respond efficiently.
  + Theme 1: **Pre-emergence** – Predicting and detecting rare events in complex, dynamical systems 
  + Theme 2: **Data, AI/ML and Design** - Computing, manufacturing and technology innovation for pandemics 
  + Theme 3: **The Host as the Universe** - Identifying host-pathogen tipping points that dictate control or spread of an infection
  + Theme 4: **Human Systems** – The role of human behavior, activities and environments in disease emergence, transmission, and response or mitigation
* Deadline: December 8, 2023 (LOI due August 25, 2023)
* Award: $15-18M for durations up to seven years

### [Cyberinfrastructure Technology Acceleration Pathway (CITAP)](https://new.nsf.gov/funding/opportunities/cyberinfrastructure-technology-acceleration){target="_blank"}
* Supports the translation of innovative research CI software, such as system software, libraries, application codes, and software enabling data services. 
* Deadline: September 6, 2023
* Award: $10M for durations up to five years with opportunity for renewal

### [Centers for Chemical Innovation (CCI)](https://new.nsf.gov/funding/opportunities/centers-chemical-innovation-cci){target="_blank"}
*   Supports developing centers (Phase I) and large, multi-institutional research centers (Phase II) focused on major, long-term chemical research challenges.
*   Deadline: August 10, 2023 (Preliminary Proposal)
*   Award: \$1.8M for durations up to three years, eligible for Phase II (\$4M/year for durations up to five years)

### [Assessing and Predicting Technology Outcomes (APTO)](https://new.nsf.gov/funding/opportunities/assessing-predicting-technology-outcomes-apto){target="_blank"}
* Supports the assessment of how investments in science and technology research and development will contribute to specific technology outcomes: technology capabilities, technology production, and technology use. These models should be able to predict future as well as past states of technology outcomes. 
* Deadline: August 21, 2023 (Preliminary)
* Award: $500K to $4M per year for durations of one to five years

### [BioFoundries to Enable Access to Infrastructure and Resources for Advancing Modern Biology and Biotechnology (BioFoundries)](https://new.nsf.gov/funding/opportunities/biofoundries-enable-access-infrastructure){target="_blank"}
* Supports grand challenge questions requiring a deeper understanding of biological systems and technologies are as diverse as life itself. Understanding the complexity of living systems and their interactions with human-derived products and processes, ensuring the safe, ethical and equitable access to and co-generation of knowledge and products,  requires the sustained development of technologies, sophisticated instrumentation, workflow pipelines and their automation, and advanced computing that are beyond the capabilities found in the laboratories of individual investigators. 
* Deadline: October 2, 2023 (LOI due August 1, 2023)
* Award: $15-24M for durations of six years
* This is a [*limited submission opportunity*](https://utah.infoready4.com/#competitionDetail/1904678){target="_blank"} due July 11, 2023.

### [NSF Convergence Accelerator Phases 1 and 2 for the 2023 Cohort - Tracks K, L, M](https://new.nsf.gov/funding/opportunities/nsf-convergence-accelerator-phases-1-2-2023-cohort){target="_blank"}
* Supports the transition of basic research and discovery into practice—to solve high-impact societal challenges aligned with specific research themes (tracks). 
  + Track K: Equitable Water Solutions
  + Track L: Real-World Chemical Sensing Applications
  + Track M: Bio-Inspired Design Innovations
* Deadline: August 22, 2023 (LOI due July 11, 2023)
* Award: $750K for Phase 1 for durations of one year (supports application to Phase 2 for $5M total for durations of two years)

### [Building the Prototype Open Knowledge Network (Proto-OKN)](https://beta.nsf.gov/funding/opportunities/building-prototype-open-knowledge-network-proto){target="_blank"}
*   Supports the creation of a prototype Open Knowledge Network --- an essential public-data infrastructure to power the next information revolution.
*   Deadline: June 20, 2023; [(Internal LSO due April 25)](https://utah.infoready4.com/#competitionDetail/1900424){target="_blank"}
*   Award: \$1.5M for durations up to three years

### [NSF Engines Builder Platform](https://sam.gov/opp/31dc45d7b356499ab8b88a143cdf27a6/view){target="_blank"}
* Supports an organization that can help develop, launch, and run a “Builder Platform” to support its NSF Regional Innovation Engines (NSF Engines) awardees, a signature initiative of NSF’s Technology, Innovation, and Partnerships (TIP) directorate. 
* Deadline: June 12, 2023
* Award: $9.5M (total) for durations of three years

### [Spectrum and Wireless Innovation enabled by Future Technologies - Satellite-Terrestrial Coexistence (SWIFT-SAT)](https://new.nsf.gov/funding/opportunities/spectrum-wireless-innovation-enabled-future-0){target="_blank"}
* Supports research on techniques to overcome radio interference and light pollution conflicts between satellite users (communications, earth sensing) and terrestrial users (communications, astronomy) enabling usage growth to benefit society.
* Deadline: June 5, 2023
* Award: \$750K for durations up to three years

## Dear Colleague Letters
* [Workshop to Inform Development of the NSF Research on Research Security Program (RRSP)](https://www.nsf.gov/pubs/2023/nsf23126/nsf23126.jsp){target="_blank"} proposals due by September 25, 2023. Webinars on creating a Research on Research Security Program will be held July 13 and July 26. [Register now!](https://nsf.zoomgov.com/webinar/register/WN_Q538jXFsRiOmHfyI-89n8A?utm_medium=email&utm_source=govdelivery){target="_blank"}
* [Joint NSF-JST Proposals to Advance Human-Centered Data for Disaster Resilience Research (HCDDRR)](https://new.nsf.gov/funding/opportunities/joint-nsf-jst-proposals-advance-human-centered){target="_blank"} due August 18, 2023 to programs: Smart and Connected Communities (CISE), CPS-CISE, HDBE-ENG, or DRMS-SBE. <--! April 14, 2023 -->
* [**Request for Information** on the Capacity of Institutions of Higher Education to Produce Graduates with Degrees, Certifications, and Relevant Skills Related to Artificial Intelligence](https://www.nsf.gov/pubs/2023/nsf23099/nsf23099.jsp){target="_blank"} response due June 21, 2023.<!-- May 8, 2023 -->
* [**Request for Information** on Future Topics for Workforce Development in Emerging Technology Career Pathways](https://www.nsf.gov/pubs/2023/nsf23100/nsf23100.jsp){target="_blank"} response due June 21, 2023.<!-- May 8, 2023 -->
* [**Request for Input** on the Development of the U.S. Research Security and Integrity Information Sharing Analysis Organization](https://www.nsf.gov/pubs/2023/nsf23098/nsf23098.pdf){target="_blank"} response due June 30, 2023.<!-- May 4, 2023 -->
* [Supporting Cybersecurity & Privacy Education and Workforce Development](https://www.nsf.gov/pubs/2023/nsf23091/nsf23091.jsp) due by May 23, 2023. <!--April 24, 2023 -->
* [Seeking US Industry and US Federal Agency Partners to Support Research Projects in Advanced Networking Systems](https://www.nsf.gov/pubs/2023/nsf23090/nsf23090.jsp) response due May 15, 2023.<!-- April 18, 2023 -->

# Internal Funding Opportunities
### [One Utah Data Science Hub Seed Grant Program - FY24](https://utah.infoready4.com/#freeformCompetitionDetail/1913850){target="_blank"}
-   Supports the initiation of new collaborations and innovative research in data science and data-enabled science that will lead to federal extramural grant applications.
-   Deadline: December 15, 2023
-   Award: Up to \$50K for one year

### [FY24 Distinguished Research Awards](https://utah.infoready4.com/#freeformCompetitionDetail/1912040){target="_blank"}
-   The Distinguished Research Award (DRA) is a prestigious faculty award designed to recognize outstanding achievements in research by three University of Utah faculty each year.
-   Deadline: December 13, 2023
-   Award: \$10,000 grant to pursue research and/or creative pursuits and recognition at the UofU Commencement.

### [Utah CTSI Community & Academic Partnership Pilot (CAPP) Program](pdfs/CTSI CAPP FOA - final.pdf){target="_blank"}
* Supports collaborations between community organizations located in Utah and adjacent states, and CTSI-affiliated academic partners that address at least one of the following focal areas:
  + Address barriers to conducting clinical & translational research
  + Advance human health
  + Understand and reduce health disparities
* Deadline: LOI due September 15, 2023, invited full proposal due December 18, 2023
* Award: $60K for one year


# Foundation Funding Opportunities

### [Predictors of Vaccine Efficacy: Identifying Correlates of Protection](https://wellcome.org/grant-funding/schemes/correlates-protection-for-vaccine-development){target="_blank"}

-   Supports research teams to establish or validate correlates of protection across 11 diseases with the potential to cause substantial outbreaks or which have significant burden, and have no licenced vaccines.
-   Deadline: February 6, 2024 (Preliminary Application), May 21, 2024 (Full Invited Proposal)
-   Award: £5M for durations up to three years

### [Motorola Solutions Foundation Grants](https://www.motorolasolutions.com/en_us/about/motorola-solutions-foundation/annual-grants.html){target="_blank"}

-   Technology & engineering education - From engaging students through hands-on engineering activities like design, coding and robotics to providing scholarship and workforce placement for underrepresented groups, we’re committed to creating opportunities for future innovators.
-   Deadline: February 1, 2024
-   Award: \$50,000
-   Please contact [Gwen Allouch](mailto:gwen.allouch@hsc.utah.edu) if you are interested in applying to this opportunity.

### [AVDF/ACLS Fellowships for Research on the Liberal Arts](https://www.acls.org/programs/avdf-acls-fellowships-for-research-on-the-liberal-arts/){target="_blank"}
-   Supports scholarly projects that draw upon the newly available College and Beyond II (CBII) database.
-   Deadline: December 15, 2023
-   Award: \$45K, participation in a 2-day data training, and subsequent symposium

### [Simons Foundation: Scientific Software Research Faculty Award](https://www.simonsfoundation.org/grant/scientific-software-research-faculty-award/){target="_blank"}
-   Supports new research professor positions in existing academic departments to be filled by scientific software-focused researchers with an overall aim to stimulate the development and maintenance of core scientific software infrastructure in academic environments through creating a new, long-term, faculty-level career path.
-   Deadline: December 8, 2023 (LOI), February 28, 2024 (Full Proposal)
-   Award: 50% salary and \$50K allowable expenses for durations up to five years

### [Chan Zuckerberg Initiative Data Insights (Cycle 3)](https://chanzuckerberg.com/rfa/single-cell-data-insights/){target="_blank"}
-   Supports the advancement of tools and resources that make it possible to gain greater insights into health and disease from single-cell biology datasets.
-   Deadline: December 5, 2023
-   Award: \$400,000 total costs for Expanded Projects and \$200,000 total costs for Focused Projects for durations of 18-months

### [W. M. Keck Foundation](https://utah.infoready4.com/#competitionDetail/1919629){target="_blank"}
-   Supports interdisciplinary and transformative project concepts for the W. M. Keck Foundation. Keck seeks to benefit humanity by supporting projects in two specific areas (1) medical research and (2) science and engineering.
-   Deadline: December 4, 2023 ([Internal LSO](https://utah.infoready4.com/#competitionDetail/1919629){target="_blank"})
-   Award: up to \$1.4M over three years

### [Russel Sage Foundation: Future of Work](https://www.russellsage.org/research/funding/future-work){target="_blank"}
* Supports innovative research on the causes and consequences of changes in the quality of jobs for low- and moderately paid workers and their families in the U.S. 
* Deadline: November 7, 2023 (Letter of Inquiry), Invited Proposals due February 21, 2024
* Award: Up to $200K over two years

### [Russel Sage Foundation: Behavioral Science and Decision Making in Context](https://www.russellsage.org/research/funding/behavioral-science-decision-making){target="_blank"}
* Supports perspectives from multiple disciplines, including economics, psychology, political science, sociology, law, public policy, and other social sciences, to further our understanding of economic, social, and political decision-making processes, attitudes, behaviors, and institutional practices in public and private contexts such as policing/criminal legal systems, employment, housing, politics, racial/ethnic relations, and immigration. 
* Deadline: November 7, 2023 (Letter of Inquiry), Invited Proposals due February 21, 2024
* Award: Up to $200K over two years

### [CIFAR Azrieli Global Scholars](https://cifar.ca/wp-content/uploads/2023/08/GlobalScholar_ProgramOverview2023.pdf){target="_blank"}
* CIFAR invites outstanding early-career researchers from across the natural, biomedical, life and social sciences and the humanities to join  one of our interdisciplinary research programs that address some of the most important questions facing science and humanity. 
* Deadline: October 30, 2023
* Award: $100K CAD, mentorship, seed funding, and leadership development

### [Rose Foundation: Consumer Privacy Rights Fund](https://rosefdn.org/wp-content/uploads/Consumer-Privacy-2023-RFP.pdf){target="_blank"}
* Supports privacy protection and privacy education efforts, specifically individual consumer’s internet privacy rights.
* Deadline: October 13, 2023
* Award: $150K

### [The Chan Zuckerberg Initiative (CZI), The Kavli Foundation, and The Wellcome Trust: Essential Open Source Software for Science](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/){target="_blank"}
* Supports open source software projects essential for biomedical research. The goal of the program is to support software maintenance, growth, development, and community engagement for these critical tools.
* Deadline: October 17, 2023 (LOI); December 5, 2023 for invited full proposals
* Award: $50-200K/year for durations of two years

### [Ford Foundation: 2023 Digital Infrastructure Insights Fund](https://fordfoundation.forms.fm/2023-digital-infrastructure-insights-fund-rfp/forms/9724){target="_blank"}
* The D//F (Digital Infrastructure Insights Fund) is a multi-funder initiative by Ford Foundation, Alfred P. Sloan Foundation, Omidyar Network, Schmidt Futures and Open Collective sustaining a platform for researchers and practitioners to better understand how open digital infrastructure is built and deployed.
* Deadline: September 30, 2023
* Award: $50-125K for durations of six to twelve months

### [Polycystic Kidney Disease (PKD) Foundation Research Grant](https://pkdcure.org/research-medical-professionals/research-funding/apply-for-funding/pkd-foundation-research-rfa/){target="_blank"}
-   The PKD Foundation's principal mission is to support basic, translational, and clinical research that will benefit patients with autosomal dominant and autosomal recessive polycystic kidney disease (ADPKD and ARPKD).
    -   Epidemiology/data analysis research --- to conduct secondary data analyses utilizing existing database resources, or to develop new statistical methodologies or test hypotheses using [existing data](https://pkdcure.org/research-medical-professionals/data-resources-in-pkd-research/){target="_blank"}.
-   Deadline: August 14, 2023
-   Award: \$80K per year for durations up to three years

### [Health Data for Action (HD4A, Data Access Award)](https://www.rwjf.org/en/grants/active-funding-opportunities/2023/health-data-for-action-data-access-award.html){target="_blank"}
-   Supports free access to selected data sets, while limited funding is available for a small number of projects from First-Time Investigators who will receive both funds and access to conduct studies using selected data sets.
-   Deadline: August 18, 2023 (brief proposal)
-   Award: data access for durations one to two years with up to \$100K for first-time investigators
-   Optional informational webinar on July 18 at 11 am ([registration required](https://academyhealth.org/events/2023-07/webinar-health-data-action-2023-applicant-information-session){target="_blank"})

### [Mozilla Data Futures Lab Infrastructure Fund](https://foundation.mozilla.org/en/data-futures-lab/grantmaking/infrastructure-fund/){target="_blank"}
-   Supports the development of open source software needed to foster a more fair and just data ecosystem.
-   Deadline: *Letter of Intent* August 31, 2023
-   Award: *Idea* phase \$10K; *Development/testing* phase \$25K; *Launched*, in-use project (milestone deliverable) \$50K

### [Digital Assessment Tools for FTD and ALS](https://www.als.org/research/funding-opportunities/digital-assessment-tools-ftd-and-als-2023){target="_blank"}
-   Supports the development of digital tools with broad applicability across the FTD-ALS spectrum beyond the discovery stage toward validation with two types of projects:
    -   *Advancing Tool Development*
    -   *Creating a Conceptual Model as a Guide for Digital Outcome Assessment Development*
-   Deadline: July 14, 2023
-   Award: \$150-400K for durations up to two years

### [PhRMA Foundation: Faculty Starter Grant in Drug Discovery Targets and Pathways](https://www.phrmafoundation.org/awards/faculty-starter-grants/drug-discovery/)
* Supports individuals beginning independent careers in drug discovery research at the faculty level at an accredited U.S. university.
* Deadline: July 1, 2023 (LOI due May 15, 2023)
* Award: $100K for one year

###  [RWJF: Data Visualization of Structural Racism and Place](https://www.rwjf.org/en/grants/active-funding-opportunities/2023/data-visualization-of-structural-racism-and-place.html)
* Supports the creation of data visualizations as tools to provide an understanding of structural racism's impact on place, health, and wellbeing.
* Deadline: June 2, 2023 ([Internal LSO due May 12](https://utah.infoready4.com/#competitionDetail/1903724))
* Award: Typically \$100-250K for one year


# Industry Funding Opportunities
### [Google Research Scholar Program](https://research.google/outreach/research-scholar-program/){target="_blank"}
-   Supports professors globally who are teaching at universities and meet the eligibility requirements. It is our hope that this program will help develop collaborations with new professors and encourage the formation of long-term relationships. Supports cutting-edge research in the fields of algorithms and optimization, health research, machine learning and data mining, natural language processing, quamtum computing, software engineering and programming languages, fundamental and applied science, human-computer interaction, machine perception, privacy, security, and systems and networking systems.
-   Deadline: November 30, 2023
-   Award: \$60K

### [Amazon Research Awards](https://www.amazon.science/research-awards/call-for-proposals){target="_blank"}
* Supports research programs in the following themes:
  + AI for Information Security
  + Automated Reasoning
  + AWS AI
  + AWS Cryptography and Privacy
  + AWS Database Services
  + Sustainability
* Deadline: November 1, 2023
* Award: Varies; up to $100K unrestricted funds, $50K AWS credits, and training resources 

### [Microsoft Accelerate Foundation Models Research](https://www.microsoft.com/en-us/research/academic-program/accelerate-foundation-models-research-fall-2023){target="_blank"}
* Supports leading foundation models hosted by Microsoft Azure more accessible to the academic research community via Microsoft Azure AI services. By driving deeper collaboration across disciplines, institutions, and sectors, we aim to unlock the full potential of AI across greater breadth of research pursuits, application domains, and societal contexts.
  + Align AI systems with human goals and preferences
  + Advance beneficial applications of AI
  + Accelerate scientific discovery in the natural and life sciences
* Deadline: September 12, 2023
* Award: Up to $20K Azure Credits, access to Azure OpenAI Service and open-source models

### [LTC Data Cooperative: Real World Data Scholars Program](https://impactcollaboratory.org/ltc-real-world-data-scholars-program/){target="_blank"}
-   Supports the development of advanced graduate students, postdoctoral fellows, and early-career faculty who are interested in developing their expertise and experience in working with electronic health record (EHR) data.
-   Deadline: August 4, 2023
-   Award: \$50K (direct) for one year

### [Permanente Medical Group: Artificial Intelligence and Machine Learning in Healthcare Grants](https://divisionofresearch.kaiserpermanente.org/projects/aim-hi?kp_shortcut_referrer=kp.org/aim-hi){target="_blank"}
-   Supports research that evaluates the implementation of existing Artificial Intelligence/Machine Learning algorithms that enhance diagnostic decision making to achieve the following objective: to advance research methods, identify best practices for scalability, and build capacity for effectively implementing and rigorously evaluating the use of AI/ML algorithms for diagnostic decision-making in real-world settings.
-   Deadline: October 13, 2023 (LOI due June 30, 2023)
-   Award: \$750K
-   Please contact [Lynn Wong](mailto:lynn.wong@hsc.utah.edu) if you are interested in applying for this opportunity.

### [OpenAI, Inc.: Pilot Grants for Democratic Inputs to Artificial Intelligence](https://openai.com/blog/democratic-inputs-to-ai){target="_blank"}
* Supports experiments in setting up a democratic process for deciding what rules AI systems should follow within the bounds defined by the law.
* Deadline: June 24, 2023
* Award: $100K
* Please contact [Gwen Allouch](mailto:gwen.allouch@hsc.utah.edu) if you are interested in applying to this opportunity.

### [AWS AI: Generative AI call for proposals — Spring 2023](https://www.amazon.science/research-awards/call-for-proposals/aws-ai-generative-ai-call-for-proposals-spring-2023)
* Supports proposals that focus on innovation related to supporting annotators with machine learning and artificial intelligence.
* Deadline: April 26, 2023
* Award: $70K unrestricted funds, $50K AWS promotional credits

### [AWS IMAGINE: The Go Further, Faster Award](https://aws.amazon.com/government-education/nonprofits/aws-imagine-grant-program)
* Support for highly innovative projects that leverage the cloud. These projects will have the potential to produce scaled, repeatable solutions and may impact an entire industry or field.
* Deadline: June 1, 2023
* Award: $150K unrestricted funds, $100K AWS promotional credits

### [AWS IMAGINE: The Momentum to Modernize Award](https://aws.amazon.com/government-education/nonprofits/aws-imagine-grant-program)
* Supports nonprofit organizations seeking to transform and enhance their core mission operations with technology, many organizations need funding for foundational technology projects, such as migrating servers to the cloud and modernizing new and existing applications.
* Deadline: June 1, 2023
* Award: $50K unrestricted funds, $20K AWS promotional credits

# International Funding Opportunities
### [Critical and Emerging Technology: Quantum Technologies and Artificial Intelligence for Transforming Lives](https://cet.usistef.online/login){target="_blank"}
-   India and the United States are building a comprehensive roadmap for partnership in crucial areas of mutual interest while emphasizing the importance of leveraging complementary strengths and addressing critical challenges. In alignment with the recent U.S.-India initiative on Critical and Emerging Technology (CET), to strengthen links and enhance technology cooperation between the innovation ecosystems of both nations, the United States--India Science & Technology Endowment Fund (USISTEF) announces this special call.
    -   *Quantum Technologies*: The joint proposals focus on innovation pertinent to the scaling-up and application of emerging quantum technologies.
    -   *Artificial Intelligence*: The joint proposals to support a team deploy and commercialize a laboratory-validated prototype that ensures and demonstrates advanced innovation and societal impact.
-   Deadline: August 31, 2023
-   Award: \$120K (10M INR) for durations of two years

### [Generative AI Skills Challenge](https://data.org/initiatives/ai-challenge/){target="_blank"}
-   A global grant for organizations training and upskilling teams on generative AI to drive social impact. With a particular focus on fair and community-led integration in low- and middle-income countries and contexts (LMICs), the Challenge aims to accelerate digital inclusion, socioeconomic mobility, and skills advancement and acquisition for workers from historically marginalized populations around the world.
-   Deadline: August 15, 2023
-   Award: \$250K for durations of 7-8 months
-   [Q&A Session on August 2, 2023 at 7am MT](https://events.teams.microsoft.com/event/2d44f676-6b1e-49e1-b5d8-e88125e99da1@4ff91a0d-0e02-4e46-8d31-b793d477b044)


# Governmental Funding Opportunities

### [Boosting Innovative GEOINT - Topic 1: Geospatial-Intelligence Foundational Model (GFM)](https://www.grants.gov/search-results-detail/351404){target="_blank"}

-   Supports innovative concepts to address hard GEOINT problems that align to one or more of the following technical domains: (1) Foundational GEOINT, (2) Advanced Phenomenologies, and (3) Analytic Technologies.
-   Deadline: January 23, 2024 (Abstracts); March 4, 2024 (Proposal); Additional topics added through 2026
-   Award: \$3M for one year

### [I-ARPA Securing Our Underlying Resources in Cyber Environments (SoURCE CODE) Program](https://sam.gov/opp/fba8e8b62bbf437da4ca1db186b0a7dd/view){target="_blank"}

-   Supports novel technologies to assist forensic experts in making determinations of the most likely attackers, based on coding styles. The program will explore full feature spaces in binary code and source code files to measure the similarity between files and provide information to forensic experts to the likely origins (country, groups, individuals, etc.).
-   Deadline: January 22, 2024

### [NASA ROSES: Heliophysics Artificial Intelligence/Machine Learning-Ready Data](https://nspires.nasaprs.com/external/solicitations/summary.do?solId=%7B8721DD55-91A7-4355-4EFB-9224A6C9462A%7D){target="_blank"}
-   Supports the advancement of the goals and objectives of NASA Heliophysics by developing new tools and methods for the generation of AI/ML-ready datasets from existing research and mission data.
-   Deadline: January 18, 2024 (Step 1, preliminary proposal); April 18, 2024 (Step 2, full proposal); repeated annually
-   Award: Dependent on scope of project

### [I-ARPA Bias Effects and Notable Generative AI Limitations (BENGAL) Targeted Super Seedling Research Topics](https://sam.gov/opp/affad5d251934a2a8c4c8e4c9f33433d/view){target="_blank"}
-   Supports new capabilities to enable the safe adoption and use of generative AI technologies to greatly enhance the effectiveness and efficiency of the Intelligence Community (IC). The goal of the BENGAL targeted super seedling is to understand LLM threat modes, quantify them and to find novel methods to correct threats and vulnerabilities or to work resiliently with imperfect models.
-   Deadline: January 19, 2024 (ENCOURAGED: white papers due December 5, 2023)

### [ARPA-H: Biomedical Data Fabric Toolbox](https://sam.gov/opp/d4d90aff105c4ffebe264a47642deef3/view){target="_blank"}
-   Supports innovative proposals for research and development (R&D) in data integration and usability technologies. Proposed R&D should investigate innovative software approaches that enable revolutionary advances in the collection and usability of biomedical datasets that originate from thousands of different research labs, clinical care centers, and other sources of data in order to accelerate technical innovation across the health ecosystem.
-   Deadline: November 28, 2023
-   Award: Varies based on the project scope (BIT, BYTE and KILO scales solicited)

### [NOAA, DOC: FY2024 Weather Program Office Research Programs](https://www.grants.gov/web/grants/view-opportunity.html?oppId=350001){target="_blank"}
* Supports new weather, water, and earth system observing and forecasting applications.
  + *Climate Testbed (CTB)* - for proposals to advance NOAA’s operational subseasonal-to-seasonal (two weeks to two years) prediction capabilities via the NOAA CTB. The portfolio will prioritize capabilities that enhance operational prediction systems, products, or research that aims to transition to operations, with a preference toward activities that enhance or improve precipitation outlooks and service delivery. One to two awards are expected of up to $300,000 per year.
  + *Fire Weather* - for research and development proposals to improve fire weather forecast information and delivery. This opportunity will support new research into the coupled Unified Forecast System for the short-term fire-atmosphere modeling systems. Two to three awards are expected of up to $350,000.
* Deadline: November 16, 2023
* Award: $300K per year

### [DOT: Advanced Driver Assistance Systems Microsimulation Model Development and Validation](https://sam.gov/opp/1de4f24e721944fabbb58e0e97893382/view){target="_blank"}
* Supports development of models that describe how Advanced Driver Assistance Systems (ADAS) and Automated Driving Systems (ADS)—with or without connectivity—operate in traffic. The models proposed in response to this proposal request should seek to fill gaps in current traffic operations modeling capabilities.
* Deadline: October 6, 2023
* Award: Unspecified.

### [NEH: Dangers and Opportunities of Technology: Perspectives from the Humanities](https://www.neh.gov/program/dangers-and-opportunities-technology-perspectives-humanities){target="_blank"}
* Supports research that examines technology and its relationship to society through the lens of the humanities, with a focus on the dangers and/or opportunities presented by technology.
  +  A special encouragement for research projects that seek to understand and address the ethical, legal, and societal implications of artificial intelligence (AI).
* Deadline: October 11, 2023
* Award: Up to $150K for durations of two years
* [Q&A Session on August 15 at 12pm MT](https://events.gcc.teams.microsoft.com/event/9fd1d723-2090-4ebb-982b-f38ad71ce770@93b06459-c77d-44b6-af7f-e813cddcdcc3)

### [DARPA: Adversarial Resilient Cyber Effects for Decision Dominance Collaborative Research Program](https://www.grants.gov/web/grants/view-opportunity.html?oppId=349875){target="_blank"}
* Supports expansion of theoretical and scientific understanding of cyberspace windows of superiority (CWoS), such that one can rapidly and reliably identify, predict, and create these windows to provide military and civil leadership with multiple courses of action. Including research thrusts:
  + Explore and define CWoS: Identify and Predict CWoS, Create CWoS
  + Adversarial Resilient Cyber: Multidomain Cyber Deception in Contested Environments, Machine Learning for Security and Security for Machine Learning
* Deadline: October 13, 2023
* Award: Unspecified, budget must be align with the project scope

### [Office of Postsecondary Education (OPE): Higher Education Programs (HEP): Fund for The Improvement of Postsecondary Education (FIPSE): Postsecondary Student Success Grant](https://www.grants.gov/web/grants/view-opportunity.html?oppId=349499){target="_blank"}
-   Supports equitable improvement for postsecondary student outcomes, including retention, transfer (including successful transfer of completed credits), credit accumulation, and completion, by leveraging data and implementing, scaling, and rigorously evaluating evidence-based activities to support data-driven decisions and actions by institutional leaders committed to inclusive student success.
-   Deadline: September 25, 2023
-   Award: \$1.75M

### [NIH NPH: AIMINGS AI for Precision Nutrition Pilot Program Round Two](https://www.phicor.org/rfa){target="_blank"}
-   Supports research projects that develop and utilize artificial intelligence (AI) and other computer-aided approaches to facilitate precision nutrition.
-   Deadline: October 2, 2023
-   Award: \$125K (total) for one year
-   **Informational Webinar**: July 20, 2023 at 1:30pm, register [here](https://www.eventbrite.com/e/aimings-ai-for-precision-nutritions-applicant-informational-webinar-tickets-668966997297?aff=oddtdtcreator).

### [ARPA-H: Scaling Health Applications Research for Everyone (SHARE)](https://sam.gov/opp/161668cf86cb4c5da64cbe2e1ce17110/view){target="_blank"}
-   Supports proven technologies developed for national security and apply them to civilian health systems, clinical care facilities, and personal health devices.
  + [DIGIHEALS Project](https://arpa-h.gov/news/digiheals/){target="_blank"} to protect the U.S. healthcare system’s electronic infrastructure
-   Deadline: September 7, 2023
-   Award: Unspecified, budget must be align with the project scope

### [NEH: Humanities Connections](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348280){target="_blank"}
-   Supports the planning or implementation of curricular projects connecting the humanities to the physical and natural sciences; pre-service or professional programs, including law and business; computer science, data science, and other technology-driven fields; or other non-humanities departments or schools.
-   Deadline: September 7, 2023 (Optional draft due July 21, 2023)
-   Award: \$50K for planning for 1 year, \$150K for implementation for 1.5 to 3 years

### [DoD: Prostate Cancer, Data Science Award](https://www.grants.gov/web/grants/view-opportunity.html?oppId=347770){target="_blank"}
-   Supports research where quantitative and analytical approaches, processes, and/or systems are developed and/or used to obtain knowledge and insight from large and/or complex sets of prostate cancer data.
-   Deadline: August 24, 2023
-   Award: \$1M direct

### [US Economic Development Administration: Regional Technology and Innovation Hubs (Tech Hubs) Phase 1](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348101){target="_blank"}
-   Supports consortia through an economic development initiative designed to drive regional technology- and innovation-centric growth by strengthening a region's capacity to manufacture, commercialize, and deploy critical technologies.
-   Deadline: August 15, 2023
-   Award: \$500K, ability to apply for Phase 2

### [Bureau of Cyberspace and Digital Policy: Responsible State Behavior in Cyberspace Capacity Building](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348759){target="_blank"}
-   Supports partnership with a capable organization(s) to develop curriculum and provide capacity building for two complementary, yet distinct, focal areas that seek to improve international stability in cyberspace.
-   Deadline: August 4, 2023
-   Award: \$500K-\$1M

### [Bureau of Cyberspace and Digital Policy: AI Connect II](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348758){target="_blank"}
-   Supports partnership with a capable organization to build the Promoting American Leadership, Democratic Values, and Economic Prosperity in Artificial Intelligence project by engaging with the AI Connect multi-stakeholder community and encouraging the responsible stewardship of AI technologies in line with the OECD AI Principles that empowers low- and middle-income countries to participate in the global, multi-stakeholder conversations more effectively on AI policy.
-   Deadline: August 4, 2023
-   Award: \$1M

### [Bureau of Cyberspace and Digital Policy: Global Cyber and Digital Policy Training](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348757){target="_blank"}
-   Supports partnership with a capable organization to develop curriculum and provide training to international entities and personnel for the development of responsible cybersecurity and digital policy.The training is intended to provide specialized and technical in-person capacity building training to primarily but not limited to government officials, from developing countries that are key stakeholders in cyber and digital policy in their respective countries, regional or multilateral institutions.
-   Deadline: August 4, 2023
-   Award: \$2.6M

### [NIST: Regional Alliances and Multistakeholder Partnerships to Stimulate (RAMPS) Cybersecurity Education and Workforce Development](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348550){target="_blank"}
-   Supports activities to establish community-based partnerships to develop cybersecurity career pathways that address local workforce needs.
-   Deadline: August 7, 2023
-   Award: \$200K for durations up to two years

### [National Center for Health Statistics: National Vital Statistics System Modernization---New Opportunities for Interoperable Data](https://www.americasdatahub.org/opportunities/){target="_blank"}
-   Supports opportunities for the use of interoperable health data to support timely research and public health surveillance. Insights from this project will help to modernize health data interoperability that can inform best practices for a possible, future National Secure Data Service (NSDS) and the broader data and evidence ecosystem.
-   Deadline: July 6, 2023
-   Award: \$300K

### [Expanding Equitable Access to Restricted-Use Data through Federal Statistical Research Data Centers](https://www.americasdatahub.org/opportunities/){target="_blank"}
-   Supports assessment of future capabilities of a National Secure Data Service (NSDS) by strategically examining user demand/needs of the Federal Statistical Research Data Center (FSRDC) network and by establishing a targeted pilot program to make funding supports available among underserved communities and institutions.
-   Deadline: July 6, 2023
-   Award: \$500K

### [National Geospatial-Intelligence Agency, Boosting Innovative GEOINT - Research, Broad Agency Announcement (NGA BIG-R BAA)](https://sam.gov/opp/99962bd4a4524805ba2e7dd7e283f12b/view){target="_blank"}
-   [Topic 10: Advanced 3D Analytic Tool Development, Enhancement, and Integration](https://sam.gov/api/prod/opps/v3/opportunities/resources/files/563f93eaa9814df0950a39e1a74c65fa/download?&token=)
-   Deadline: July 28, 2023 (Abstract due June 26, 2023)
-   Award: Up to \$8M in total awards for several technical elements

### [Utah System of Higher Education: Computer Science Targeted Workforce Initiative Grant](https://drive.google.com/file/d/1aLPZH-mcI_BBuVslNrNlWiweOnvx86bF/view){target="_blank"}
-   Supports the creation and/or expansion of capacity in computer science workforce education programs to include: Information Security Analysts, Software Developers and QA Analysts, Digital Interface Designers, Computer and Information Research Scientists, Database Administrators, and Architects.
-   Deadline: *EXTENDED* June 29, 2023, recurring quarterly if funds remain
-   Award: Unspecified, \$4.5M available

### [Utah System of Higher Education: Healthcare Targeted Workforce Initiative Grant Request for Proposals](https://drive.google.com/file/d/1aLbxQh74PyzdtrCKzd3WfXWBRtfnyEpg/view){target="_blank"}
-   Supports the creation and/or expansion of capacity in healthcare workforce education programs to include: Respiratory Therapists, Registered Nurses, Licensed Practical Nurses, Radiology Technologists, Surgical Technologists, Diagnostic Medical Sonographers, Behavioral Health, Psychiatric Technicians, and/or Behavioral Management Specialists.
-   Deadline: *EXTENDED* June 29, 2023, recurring quarterly if funds remain
-   Award: Unspecified, \$4.5M available

### [HHS: Career Pathways Secondary Data Analysis Grants](https://www.grants.gov/web/grants/view-opportunity.html?oppId=344009){target="_blank"}
-   Supports secondary analysis of data collected to rigorously evaluate a collection of career pathways programs. The purpose of these awards is to better understand the effectiveness of services funded by Temporary Assistance for Needy Families (TANF) programs that aim to address the employment and self-sufficiency needs of TANF recipients and those eligible for or at risk of TANF receipt.
-   Deadline: June 29, 2023
-   Award: \$100K

### [Institute of Education Sciences Applications (IES): Statewide Longitudinal Data Systems (SLDS)](https://www.grants.gov/web/grants/view-opportunity.html?oppId=347943)
* Supports state educational agency to design, develop, and implement statewide longitudinal data systems to efficiently and accurately manage, analyze, disaggregate, and use individual student data. 
* Deadline: June 29, 2023 (LOI due May 19, 2023)
* Award: $4M

### [CDC: Centers for Outbreak Analytics and Disease Modeling](https://www.grants.gov/web/grants/view-opportunity.html?oppId=345850)
* Supports the development of a network of innovators to design, prototype, test, and scale innovative capabilities for improving analytics, modeling and forecasting to support decision makers during outbreaks of infectious diseases (both known and newly emerging) in the United States. 
  + *Mandatory Component 1 (Outbreak Analytics and Disease Modeling Public Health Response)*: 13 awards of $500,000 each.   
  + *Optional Component 2 (Innovations in Outbreak Analytics and Disease Modeling)*: 5 awards of $3 million each.
  + *Optional Component 3 (Integration of Outbreak Analytics and Disease Modeling into Practice)*: 5 awards of $3 million each.
  + *Optional Component 4 (Centers for Implementation in Outbreak Analytics and Disease Modeling)*: 3 awards of $5 million each.
  + *Optional Component 5 (Coordinator for the Outbreak Analytics and Disease Modeling Network)*: 1 award of $1 million.
* Deadline: June 13, 2023
* Award: Varies, see above.

### [US Army: xTechPrime Competition - Concept White Paper](https://www.challenge.gov/?challenge=xtech-prime)
* Supports small businesses and technology integrators, in the areas of Artificial Intelligence/Machine Learning, Autonomy, Climate and Clean Technologies, Immersive/Wearables, and Sensors, to engage with the DoD, earn prize money, participate in the accelerator program and submit for a Direct to Phase II SBIR award.
* Deadline: June 7, 2023
* Award: Participation in the accelerator program and submit for a Direct to Phase II SBIR award

### [IARPA: Rapid Explanation, Analysis and Sourcing Online (REASON)](https://www.iarpa.gov/research-programs/reason)
* Supports novel technologies that will enable intelligence analysts to substantially improve the evidence and reasoning in draft analytic reports.
  + Task Area 1 (TA1) – Identify Additional Evidence
  + Task Area 2 (TA2) – Identify Reasoning Strengths and Weaknesses
  + Task Area 3 (TA3) – Produce Comments to Increase Quality of Argumentation
* Deadline: May 8, 2023

## Challenges, Awards, and Other Opportunities

-   [NIH Pioneering Research for Early Prediction of Alzheimer's Disease & Related Dementias (PREPARE) Challenge](https://www.challenge.gov/?challenge=prepare-challenge){target="_blank"} seeks to advance solutions for accurate, innovative, and representative early prediction of AD/ADRD through three challenge phases that successively build on each other. Phase 1 open until January 31, 2024, \$650K in total prizes.
-   [Cyber Defensive Capability Performance Measurement Development Challenge](https://www.challenge.gov/?challenge=cyber-defensive-capability-performance-measurement-development-challenge){target="_blank"} seeks undergraduate and graduate students to develop algorithms to measure a system’s ability to maintain critical functionality during a cyberspace attack from Advanced Persistent Threat (APT) actors. The developed algorithms are to: (a) measure the effectiveness of a system’s cyber defensive capabilities against full spectrum cyber threats, and (b) calculate the cyber resiliency of the system based on given system architecture, critical functions, and the defined cyber APTs. Phase 1 open until January 26, 2024, \$125K in total prizes.
-   [The FTC Voice Cloning Challenge](https://www.ftc.gov/news-events/contests/ftc-voice-cloning-challenge){target="_blank"} supports the development of multidisciplinary approaches---from products to policies to procedures---aimed at protecting consumers from AI-enabled voice cloning harms, such as fraud and the broader misuse of biometric data and creative content. The goal of the Challenge is to foster breakthrough ideas on preventing, monitoring, and evaluating malicious voice cloning. Abstracts and detailed explanations due January 12, 2024.
-   [Open AI Preparedness Challenge](https://openai.com/form/preparedness-challenge){target="_blank"} responses will be accepted on a rolling basis through December 31, 2023. We will offer \$25,000 each in API credits to up to 10 top submissions, publish novel ideas and entries, and look for candidates for Preparedness from among the top contenders in this challenge.
-   Two Traineeship Opportunities with AIM-AHEAD, applications due date EXTENDED to December 11, 2023.
    -   [Traineeship in Advanced Data Analysis using the All of Us Clinical Database](https://www.aim-ahead.net/data-science-training-core/aim-ahead-all-of-us-training-program/){target="_blank"}
    -   [Traineeship in Advanced Data Analysis using the NCATS data and the N3C enclave](https://www.aim-ahead.net/data-science-training-core/aim-ahead-and-ncats-training-program/){target="_blank"}
-   [**Request for Information** Consultations on Sustaining Biodata Infrastructure and on Open Data Strategies](https://globalbiodata.org/your-views-sought-consultations-on-sustaining-biodata-infrastructure-and-on-open-data-strategies/){target="_blank"} from the Global Biodata Coalition is seeking feedback and inputs from our communities on how research funders could extend partnerships and work together in new ways to secure and sustain the global biodata resource infrastructure and maximize the long-term value of open research data in the life and biomedical sciences. Responses due December 4, 2023.
-   [Berkeley Computing, Data Science, & Society Spring 2024 Discovert Project Program](https://docs.google.com/forms/d/e/1FAIpQLSffZOJmUsObubwcR0f04_sYYtZgffUODsfMlynNRbqJvJ2bsw/viewform?pli=1){target="_blank"} is seeking Partners to design projects so that a team of students can be engaged over the course of a single or multiple semesters (a semester is about 12 weeks of work). Application deadline in November 30, 2023.
-   [Microsoft Research AI & Society Fellows](https://www.microsoft.com/en-us/research/academic-program/ai-society-fellows/overview/){target="_blank"} supports research collaboration between Microsoft Research and eminent scholars and experts across a range of disciplines core to discussions at the intersection of AI and its impact on society. Applications due November 29, 2023.
    -   AI in Organizational Settings
    -   AI in the Production of Culture, Media, and the Arts
    -   AI Powered Community Micro-Grid for Resiliency and Equitability
    -   Copyright Protection for User Data in the Era of LLMs
    -   Generative AI and Plural Governance: Mitigating Challenges and Surfacing Opportunities
    -   Multimodal Knowledge Understanding and Representation for Population-scale Copilots
    -   Reducing the Digital Divide of Generative AI in the Global South
    -   Regulating AI in Light of the Challenges of Doing Responsible AI in Practice
    -   Regulatory Innovation to Enable Use of Generative AI in Drug Development
    -   Sociotechnical Approaches to Measuring Harms Caused by AI Systems
    -   Storytelling and Futurism
    -   Supporting the Responsible AI Red-Teaming Human Infrastructure
    -   Towards Creative-Centered AI: Opportunities and Challenges at the Intersection of Creatives, AI, and Society
* [The White House Office of Science & Technology Policy Open Science Recognition Challenge](https://portal.challenge.gov/public/previews/challenges?challenge=0a53c056-675b-44a4-860e-a56ce3f4aaad){target="_blank"} invites researchers, community scientists, educators, innovators, and members of the broader public to share stories of how they’ve advanced equitable open science. Submissions due November 22, 2023. 
* [NIH Build UP Trust Challenge](https://www.builduptrust.org/){target="_blank"} seeks solutions that increase research participation and the adoption of medical care by building trust and improving engagement with historically underserved communities. Register by November 14, 2023, submission by December 5, 2023, awards up to $45K. 
* [Instructional System Design (ISD) Analysis Using AI Large Language Models Automate ISD Analysis and Requirements Development for Ready Relevant Learning (RRL)](https://www.challenge.gov/?challenge=instructional-system-design-isd-analysis-using-ai-large-language-models){target="_blank"} hopes to identify solutions that address a critical barrier in effectively implementing Instructional Systems Design (ISD) Analysis for training for military readiness and human performance. Registration required by October 30 with applications due November 13, 2023. 
* [BII & Science Prize for Innovation](https://bii.dk/community/scienceprize/){target="_blank"} encourages more scientists to translate their research and recognizes bold researchers who are asking fundamental questions at the intersection of the life sciences and entrepreneurship. 1000-word essay applications due November 1, 2023.
* [Learning Engineering Tools Competition - Preparing for the 21st Century World](https://tools-competition.org/)is a multi-million dollar competition for edtech innovation that leverages digital technology, big data, and learning science to meet the urgent needs of learners worldwide. Abstracts due November 10, 2023
* [NIDDK Central Repository Data-Centric Challenge - Enhancing NIDDK datasets for future Artificial Intelligence (AI) applications](https://www.challenge.gov/?challenge=niddk-central-repository-data-centric-challenge&tab=overview){target="_blank"}is aimed at augmenting existing Repository data for future secondary research including data-driven discovery by artificial intelligence (AI) researchers. Registration due October 20, 2023. 
* [HHS, CDC, and NASA: Unsupervised Wisdom: Explore Medical Narratives on Older Adult Falls](https://www.challenge.gov/?challenge=unsupervised-wisdom-explore-medical-narratives-on-older-adult-falls){target="_blank"}. The goal in this challenge is to identify effective methods of using unsupervised machine learning to extract insights about older adult falls from Emergency Department narratives. Analysis and executive summary due October 6, 2023 for cash prizes up to $20K.
* [Research Rovers: AI Research Assistants for NASA](https://www.drivendata.org/competitions/252/ai-research-assistants/page/780/){target="_blank"} is seeking innovative approaches to help assess emerging capabilities in AI-based research assistants. Solutions are due October 2, 2023.
* [ReachU Challenge](https://www.challenge.gov/?challenge=reachu-challenge){target="_blank"} calls on university and college students, researchers, faculty, and staff: where do you find funding or share your ideas for the chance to win cash prizes? Help Challenge.Gov reach YOU! **What are the best digital channels, forums, databases, or platforms to reach academic audiences about federally sponsored prize competitions, challenges, and crowdsourcing campaigns?** Ideas due by September 8, 2023. 
-   [2023 DataWorks! Prize **Deadline Extended**](https://www.herox.com/dataworks){target="_blank"} will recognize and reward exceptional data practices in biological and biomedical research labs during the active phase of research which enable robust data sharing and reuse, and create a library of best practice methods that can be used by the broader research community. Submit your data sharing/reuse best practice recipes in a form that can be used by an audience of your peers, such as a teaching resource or tool for active data management, by August 15, 2023 for a chance to win up to \$100k.
-   [Health Equity Data Access Program (HEDAP)](https://www.grants.gov/web/grants/view-opportunity.html?oppId=348252){target="_blank"} assists researchers in gaining access to CMS restricted data to conduct health services research focusing on, but not limited to, racial and ethnic minority groups; people with disabilities; members of the lesbian, gay, bisexual, transgender, and queer (LGBTQ+) community; individuals with limited English proficiency; individuals residing in rural areas; and individuals adversely affected by persistent poverty or inequality. Applications due August 15, 2023. Access will be funded for three years.
-   [Samsung AI Researcher of 2023](https://www.sait.samsung.co.kr/saithome/event/aiResearcher.do){target="_blank"} recognizes promising researchers who have made outstanding research or contributions to the field of AI. Applications are due by July 29, 2023 and the awardee will receive \$30K and plaque.
-   [The Veterans Cardiac Health and AI Model Predictions (V-CHAMPS) Challenge](https://precision.fda.gov/challenges/31){target="_blank"} calls on the scientific and data analytics community to develop and evaluate Artificial Intelligence and Machine Learning (AI/ML) models to predict cardiovascular health related outcomes in Veterans. Challenge open through July 26, 2023.

## Policy and Engagement
* [**Request for Information** on Developing a Roadmap for the Directorate for Technology, Innovation, and Partnerships at the National Science Foundation](https://www.federalregister.gov/documents/2023/04/28/2023-08995/request-for-information-rfi-on-developing-a-roadmap-for-the-directorate-for-technology-innovation){target="_blank"} response due July 27, 2023. <!-- April 28, 2023 --> 
-   [**Request for Information** National Priorities for Artificial Intelligence](https://www.whitehouse.gov/wp-content/uploads/2023/05/OSTP-Request-for-Information-National-Priorities-for-Artificial-Intelligence.pdf){target="_blank"} due by July 7, 2023.
* [Health Data, Technology, and Interoperability: Certification Program Updates, Algorithm Transparency, and Information Sharing (HTI-1) Proposed Rule](https://www.healthit.gov/topic/laws-regulation-and-policy/health-data-technology-and-interoperability-certification-program){target="_blank"} public comment period ends June 20, 2023. 