---
title: "Other Funding Opportunities"
format: html
editor: visual
---

```{=html}
<!-- ### [](){target="_blank"}
* S
* Deadline: 
* Award: $ for durations up to  years -->
```
<!-- ## Internal Funding Opportunities -->


## Foundation Funding Opportunities

### [Foresight Institute: AI Safety: Neuro/Security/Cryptography/Multipolar Approaches](https://foresight.org/ai-safety/){target="_blank"}

-   Supports projects working to make progress on three areas we consider underexplored when it comes to AI Safety.
    -   Neurotechnology, Whole Brain Emulation and lo-fi Uploading for AI safety
    -   Security, Cryptography, and Auxiliary Approaches for Infosec and AI Security
    -   Safe and Beneficial Multipolar AI Scenarios
-   Deadline: Rolling for one year until budget of \$1M is depleted <!-- August 2024 -->
-   Application should take no more than 3 hours!

### [The Michelson Prizes: Next Generation Grants](https://michelsonprizes.smapply.org){target="_blank"}
* Supports early-career scientists advancing human immunology, vaccine discovery, and immunotherapy for major global diseases, including applicants from artificial intelligence/machine learning. Please contact [Lynn Wong](mailto:lynn.wong@hsc.utah.edu) if you are interested in applying to this opportunity. 
* Deadline: June 9, 2024 (Two-page proposal)
* Award: $150K

<!--## Industry Funding Opportunities-->



## International Funding Opportunities
### [Advanced Research + Invention Agency: Safeguarded AI, TA1.1 Theory](https://www.aria.org.uk/programme-safeguarded-ai/){target="_blank"}
* Supports R&D Creators, individuals and teams to research and construct computationally practicable mathematical representations and formal semantics to support world-models, specifications about state-trajectories, neural systems, proofs that neural outputs validate specifications, and “version control” (incremental updates or “patches”) thereof.
* Deadline: May 28, 2024
* Award: £3.5M over 10-16 awards

### [Japan Science and Technology Agency: Adopting Sustainable Partnerships for Innovative Research Ecosystem (ASPIRE) Call for Proposals](https://www.jst.go.jp/inter/aspire/en/program_e/announce_e/announce_aspire2023_e.html){target="_blank"}

-   Proposals are welcomed from Japan-based researchers intending to conduct collaborative research with researchers from other advanced countries and regions in science and technology.
    -   *AI and information* research for the realization of [Society 5.0](https://www8.cao.go.jp/cstp/english/society5_0/index.html) based on the principles of human understanding and respect, diversity, and sustainability.
-   Deadline: August 17, 2024 (anticipated; recommended LOI by July 31)
-   Award: 30-100M Yen (\$200K-700K) for durations up of three to five years



## Governmental Funding Opportunities
### [NIST and DOC: Regional Alliances and Multistakeholder Partnerships to Stimulate (RAMPS) Cybersecurity Education and Workforce Development](https://www.grants.gov/search-results-detail/353143){target="_blank"}
* Supports activities to establish community-based partnerships to develop cybersecurity career pathways that address local workforce needs. Effective multistakeholder workforce partnerships will organize multiple employers with skill shortages in specific occupations to focus on developing the skilled workforce to meet industry needs within the local or regional economy.
* Deadline: May 24, 2024
* Award: Up to $200K for durations up to two years

### [EPA: Advancing Sustainable Chemistry](https://www.grants.gov/search-results-detail/353029){target="_blank"}
* Supports research for data, methods, and systems that lead to actionable, scalable change toward chemistry, chemicals, and products that support sustainable chemistry.
* Deadline: May 29, 2024
* Award: $1.5M

### [AIM-AHEAD: Federated-Network](https://www.aim-ahead.net/federated-network/){target="_blank"}
* Supports research teams from each site to (i) assemble EHR data locally from their institution to be used for AIM-AHEAD research projects; (ii) provide informatics expertise to participate in EHR data harmonization across sites; and (iii) facilitate the analysis of EHR data using AI/ML algorithms developed by the AIM-AHEAD researchers. 
* Deadline: June 3, 2024
* Award: $100K (total) for Year 1 and $300K (total) for Year 2

### [DoD: Joint Warfighter Medical Research](https://cdmrp.health.mil/funding/jwmrp){target="_blank"}
* Supports projects to augment and accelerate medical product development and health care solutions addressing virtual/telehealth and decision support with artificial intelligence solution to provide combat casualty care/prolonged care.
* Deadline: June 3, 2024 (pre-application)
* Award: $2-3.4M

### [ARPA-H: Chatbot Accuracy and Reliability Evaluation (CARE) Exploration Topic](https://sam.gov/opp/8d3c07159e9f4d32ab7b179d365e6fab/view){target="_blank"}
* Supports production of tools and technology that evaluates output with the efficiency of computational methods and the accuracy of human experts, with specific interest in development of new evaluation technologies for detecting hallucinations and other inaccuracies in medical Large Language Model (LLM) output for patient-facing applications.
* Deadline: June 3, 2024
* Award: Multiple awards are expected

### [HHS: Child Care and Development Fund (CCDF) Lead Agency Data and Research Capacity Grants](https://www.grants.gov/search-results-detail/351794){target="_blank"}
* Supports capacity of CCDF Lead Agencies to use data, including data on children, families, the workforce, and providers that participate in the child care subsidy system, to make data-informed decisions to improve child care policies and practices. 
* Deadline: July 8, 2024
* Award: $150K for durations of 18 months

### [DARPA: Microsystems Technology Office - Embedded Microsystem Intelligence and Localized Processing Thrust](https://sam.gov/opp/6214ecd14eeb41fd8103bad223837cd3/view){target="_blank"}
* Supports exploration of the development of sensors and systems that enable specialized computation at the tactical edge and microsystems capable of learning, moving beyond those with pre-set functions.
* Deadline: June 15, 2024
* Award: Multiple awards are expected

### [AIM-AHEAD: AI/ML in Biomedical Research and Clinical Practice That Embodies Ethics and Equity (ABC-EE)](https://www.aim-ahead.net/call-for-proposals-year-3/aim-ahead-ai-ml-in-biomedical-research-and-clinical-practice-that-embodies-ethics-and-equity-abc-ee/){target="_blank"}
* Supports multidisciplinary teams in the domains of biomedical research and clinical applications to develop and/or use AI/ML technologies that align with and/or extend the AIM-AHEAD ethics and equity principles. 
* Deadline: June 16, 2024
* Award: $150-250K (total) for one year

### [AIM-AHEAD: Research Fellows Program in AI/ML](https://aim-ahead.infoready4.com/#freeformCompetitionDetail/1936614){target="_blank"}
* Supports early-career researchers with the opportunity to receive funding and support for research on novel and innovative data science and data-focused research problems; specifically, those focused around health disparities and inequities.  
* Deadline: June 17, 2024
* Award: $51,840 for one year

### [AIM-AHEAD: Public-Private Partnerships to Improve Population Health Using AI/ML](https://www.aim-ahead.net/call-for-proposals-year-3/public-private-partnerships-to-improve-population-health-using-ai-ml/){target="_blank"}
* Supports mutually beneficial triadic partnerships among a 1) local, state, and tribal accredited health departments; 2) limited resource higher education institution; and 3) a data-science oriented organization with an accessible data library to collaboratively conduct health equity-related AI/ML studies that align with the overall goal of AIM-AHEAD. 
* Deadline: June 25, 2024
* Award: $525K (total) for one year

### [DoD: Prostate Cancer, Data Science Award](https://cdmrp.health.mil/funding/pcrp){target="_blank"}
* Supports research where quantitative and analytical approaches, processes, and/or systems are developed and/or used to obtain knowledge and insight from large and/or complex sets of prostate cancer data. 
* Deadline: August 9, 2024 (Pre-application), August 30, 2024 (Proposal)
* Award: Up to $1M (direct)

### [DARPA: Forward-Looking Experimentation (FLEX)](https://sam.gov/opp/80651184d8894502a3a39520e1549e57/view){target="_blank"}
* Supports fundamental research proposals for disruptive ideas in information and communication technologies (ICT) addressing the grand challenges for a data-driven future.
* Deadline: August 9, 2024
* Award: Up to $250K for up to two years

### [DARPA: Scientific Feasibility](https://www.grants.gov/search-results-detail/352745){target="_blank"}
* Supports development of computational methods that measure the feasibility of claims in order to enable accurate assessments of scientific content. The program aims to demonstrate that the scientific feasibility of claims can be determined by using automated reasoning to decompose claims into constituent, verifiable parts.
* Deadline: August 25, 2024
* Award: Multiple awards are anticipated.

### [DARPA and ARPA-H: Artificial Intelligence Cyber Challenge (AIxCC)](https://aicyberchallenge.com/){target="_blank"}
* Supports the design of novel AI tools and capabilities to find and fix vulnerabilities in software used in critical infrastructure like transportation, water and wastewater systems, emergency services, and energy sources.
* Deadline: August 2024 (Semifinal), August 2025 (Final)
* Award: 7 teams will be awarded $2M from the semifinal competition; final awards up to $4M

### [DoD and AirForce: Geospatial Intelligence Processing and Exploitation (GeoPEX)](https://sam.gov/opp/f6dac217c58545578b6dff242335e997/view){target="_blank"}

-   Supports research, development, integration, test and evaluation of technologies/techniques to provide geospatial intelligence (GEOINT) in all its forms and from whatever source to ensure a solid foundation of knowledge for planning, decision, and action while creating tailored, customer-specific geospatial intelligence, analytic services, and solutions.
-   Deadline: September 30, 2024; recurring on September 30, 2025 and September 30, 2026
-   Award: \$250K-\$10M for durations up to two years

### [APRA-H: Resilient Systems Office (RSO) Office-Wide Innovative Solutions](https://www.grants.gov/search-results-detail/352988){target="_blank"}
* Supports ground-breaking research in sociotechnical system innovation, health ecosystem integration, and adaptive and antifragile solutions to enable revolutionary advances in science, technology, systems, or methodology. 
* Deadline: March 14, 2025 (running submission)
* Awards: Multiple awards are expected

### [DARPA: Automating Scientific Knowledge Extraction and Modeling (ASKEM)](https://www.darpa.mil/program/automating-scientific-knowledge-extraction-and-modeling){target="_blank"}
-   Supports the demands of complex, modern-day systems, computational models and simulators have become the primary artifacts for encoding, propagating, and applying expert knowledge to real-world science and engineering problems.

### [DOC and NIST: Manufacturing USA AI Institute Competition](https://www.federalregister.gov/documents/2024/03/13/2024-05228/manufacturing-usa-institute-competition-ai-for-resilient-manufacturing){target="_blank"}
* Supports the use of AI to improve resilience of manufacturing within industries and sectors of national interest. The Manufacturing USA  institute will have a predominant focus on a manufacturing process, novel, material, enabling technology, supply chain integration methodology or another relevant aspect of advanced manufacturing such as nanotechnology applications, advanced ceramics, photonics and optics, composites, biobased and advanced materials, flexible hybrid technologies, tool development for microelectronics, food manufacturing, superconductors, advanced battery technologies, robotics, advanced sensors, quantum information science, supply chain water optimization, aeronautics and advanced materials, and graphene and graphene commercialization.
* Deadline and Award: To be announced in Spring 2024

## Challenges, Awards, and Other Opportunities

-   [America's Datahub Consortium Idea Bank](https://www.americasdatahub.org/idea-bank-form/){target="_blank"} invites input from stakeholders to inform future project solicitations on the topics of:

    -   Privacy Preserving Technologies (PPT)
    -   Data collection, access, linkage, and standards
    -   Statistical and other quantitative analyses
    -   Legal frameworks
    -   User Tools
    -   Stakeholder Engagement
    -   Artificial Intelligence

- [RFI: Pathways to AI-enabled research: Transforming scientific work with tools and technology](https://docs.google.com/forms/d/e/1FAIpQLSezl1aE7_czp-CQRxQX098EZTgB7T-xc5uVnVl1jMdAFTO5rw/viewform){target="_blank"} The Open Science Program at Chan Zuckerberg Initiative (CZI) and Alfred P. Sloan Foundation Technology Program (Sloan) are excited to hear community input about existing applications of AI to empower scientific work that are consistent with open research practices. Submissions accepted until May 30, 2024. 

- The National Institute of Standards and Technology (NIST) has released four draft publications intended to help improve the safety, security and trustworthiness of artificial intelligence (AI) systems [link](https://content.govdelivery.com/accounts/USNIST/bulletins/399775f){target="_blank"}. All are part of the agency’s response to Executive Order 14110 on the Safe, Secure and Trustworthy Development of AI. Comments on each draft are requested by June 2, 2024. 
  + NIST AI 600-1, Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile
  + NIST SP 800-218A, Secure Software Development Practices for Generative AI and Dual-Use Foundation Models
  + NIST AI 100-4, Reducing Risks Posed by Synthetic Content: An Overview of Technical Approaches to Digital Content Transparency
  + NIST AI 100-5, A Plan for Global Engagement on AI Standards
* Drafts of NIST AI 600-1, NIST AI 100-5 and NIST AI 100-4 are available for review and comment on the [NIST Artificial Intelligence Resource Center website](https://airc.nist.gov/AI_RMF_Knowledge_Base/Technical_And_Policy_Documents){target="_blank"}; and the draft of NIST SP 800-218A is available for review and comment on the [NIST Computer Security Resource Center website](https://csrc.nist.gov/projects/ssdf){target="_blank"}.

- [AIM-AHEAD Clinicians Leading Ingenuity IN Al Quality (CLINAQ) Fellowship Program](https://www.aim-ahead.net/call-for-proposals-year-3/aim-ahead-clinicians-leading-ingenuity-in-al-quality-clinaq-fellowship-program/){target="_blank"} is a one-year fellowship (September 16, 2024 - August 29, 2025) that seeks to operate in parallel with clinical practice to empower clinicians (defined below) in the field of Artificial Intelligence/Machine Learning (AI/ML). Applications are due by June 30, 2024. 

- [NCI Medical Image De-Identification Benchmark Challenge at MICCAI 2024](https://datascience.cancer.gov/news-events/news/participate-nci-medical-image-de-identification-benchmark-challenge-miccai-2024){target="_blank"} for developers (independent, academic, or industrial) who wants to assess your software tool’s performance with rule-based de-identification of DICOM images. Registration closes August 15, 2024.

-   [NIH and CGE Targeted Genome Editor Delivery (TARGETED) Challenge](https://www.challenge.gov/?challenge=targeted-challenge){target="_blank"} aims to revolutionize technology development of delivery systems for in vivo genome editing. This is a *\$6M competition* to improve in vivo delivery technologies for genome editors in two Target Areas: 1. Programmable delivery systems, and 2. Non-viral delivery across the blood-brain barrier. The National Institutes of Health (NIH), through the Common Fund’s [Somatic Cell Genome Editing (SCGE)](https://commonfund.nih.gov/editing){target="_blank"} program, is seeking Participants with ideas or early-stage solutions to join the Challenge with the chance to win up to \$1,000,000 and have their solution independently tested and validated in large animal models through NIH-supported independent evaluation relevant to preclinical assessments of investigational products. Phase 2 is open until January 10, 2025.

<!--## Policy and Engagement -->

Updated May 23, 2024.
