---
title: "News Highlights"
format: html
---
* [2023 Patai-Rapport Lecture Award](https://science.utah.edu/faculty/matthew-sigman-receives-the-2023-patai-rapport-lecture-award/){target="_blank"} for Matthew Sigman, Distinguished Professor and Peter J. Christine S. Stang Presidential Endowed Chair of Chemistry, is the recipient of the 2023 Patai-Rappoport Lecture Award for his major contributions in physical organic chemistry, data science and enantioselective catalysis.

* [Making machine learning accessible to all](https://attheu.utah.edu/facultystaff/making-machine-learning-accessible-to-all/){target="_blank"} UteAnalytics allows a client to clean their data and conduct exploratory data analysis in various ways.

* [Prof. Patil Selected as Faculty Co-Director of the University of Utah's DATASET Initiative](https://www.cs.utah.edu/prof-patil-selected-as-faculty-co-director-of-the-university-of-utahs-dataset-initiative/){target="_blank"}, May 31, 2023.
* [Seed grants will support U data science research](https://attheu.utah.edu/facultystaff/seed-grants-will-support-u-data-science-research/?fbclid=IwAR3j6cqf98pF0FFehnvicKumtca6IPcRquUF0cdLkz6KcwGJCXf65Rn3J6Q){target="_blank"}, February 13, 2023.
  + *Individualization of Fetal Growth Assessment using Maternal Genetics and Explainable AI*. PIs: Nathan Blue, Mark Yandell, Martin Tristani-Firouzi.
  + *A Novel Approach to Visualizing Pollution Exposure Patterns in Pregnant Women*. PIs: Simon Brewer, Michelle Debbink, Brenna Kelly. 
  + *Optimizing Across the Rashomon Set*. PI: Nina de Lacy.
  + *Predicting Perturbation Phenotypes in the Vertebrate Brain*. PIs: James Gagnon, Randall Peterson. 
  + *Use of Modularity Optimization to Define and Evaluate Regional Networks for Emergency General Surgery Care*. PIs: Marta McCrum, Joshua J. Horns, Neng Wan.
  + *CURATE Sepsis: CURating A DaTabase from the Electronic Health Records of Patients At-Risk for Sepsis*. PIs: Daniel Scharfstein, Ithan Peltan, Daniel Knox. 
  + *Machine Learning-Based Heterogeneous Treatment Effects Estimation of 2nd-line Medication Options for Type 2 Diabetes Patients Using Veteran Affairs Electronic Health Record Data*. PIs: Jincheng Shen, Srinivasan Beddhu, Tom Greene.

## Other University of Utah News
* [Most data generated is not used to its fullest potential](https://www.healthcarefinancenews.com/news/most-data-generated-not-used-its-fullest-potential?mc_cid=6cad69f6f7&mc_eid=2dd9b9f0f5){target="_blank"}, featuring *Donna Roach, Chief Information Officer*, April 17, 2023.

* [Algorithm helps predicts pneumonia risk among patients with multiple myeloma](https://www.healio.com/news/hematology-oncology/20230411/algorithm-helps-predicts-pneumonia-risk-among-patients-with-multiple-myeloma?mc_cid=6cad69f6f7&mc_eid=2dd9b9f0f5){target="_blank"}, featuring *Carrue Bellerive, Hunstman Cancer Institute*, April 15, 2023.

