---
title: "Positions and Projects"
format: html
---

## University of Utah Positions
Find a full list of active employment opportunities [here](https://utah.peopleadmin.com/){target="_blank"}!

### [Assistant or Associate Professor, Biostatistics](https://utah.peopleadmin.com/postings/153341){target="_blank"}
The [Division of Biostatistics](https://medicine.utah.edu/population-health-sciences/divisions/biostatistics){target="_blank"} in the [Department of Population Health Sciences](https://medicine.utah.edu/population-health-sciences){target="_blank"} (PHS) at the [University of Utah School of Medicine](https://medicine.utah.edu/){target="_blank"} has openings for Assistant or Associate Professor-level faculty. We are looking for candidates who will collaborate with biomedical researchers, support and develop grant proposals, teach in the Ph.D. Biostatistics program, advise graduate students, and perform methodological research. We are particularly interested in candidates who possess the research skills and experience required to successfully become leaders in multi-disciplinary research teams within the institution and in national and international research networks as well as pursue independent and collaborative methodological research in Biostatistics.

### [Assistant/Associate/Full Professor of Digital Health Applications in areas related to Diabetes, Obesity, and Metabolic Health](https://utah.peopleadmin.com/postings/153305){target="_blank"}
The University of Utah is recruiting multiple faculty members to expand its research strength in digital health applications specifically related to physical activity, nutrition, diabetes, obesity, and metabolic health. Successful candidates will be embedded in a highly collaborative environment and thriving research area at the nexus of two interdisciplinary research initiatives, the [Digital Health Initiative](https://uofuhealth.utah.edu/digital-health-initiative){target="_blank"} (DHI) and the [Diabetes and Metabolism Research Center](https://uofuhealth.utah.edu/diabetes-metabolism-research-center){target="_blank"} (DMRC). Departments/Units recruiting for these positions include Biomedical Informatics; Family and Preventive Medicine; Health & Kinesiology; Internal Medicine (Divisions of Endocrinology; Epidemiology; and General Internal Medicine); Nutrition and Integrative Physiology; Population Health Sciences; and the College of Nursing.

<!-- ### [Utah Education Policy Center (UEPC) Data Scientist](https://utah.peopleadmin.com/postings/154681){target="_blank"}
Apply your technology and analytic skills to impact today’s critical education issues as a Data Scientist for the Utah Education Policy Center (UEPC). At the UEPC you will work with experienced Education Evaluators and Researchers, as well as clients, to design and explain insights from your data analysis. Help us provide timely, high-quality, data-driven analyses to put valuable information in the hands of policy makers. -->

## External Opportunities
### [Cluster Hire in AI for Community Health: University of Illinois at Urbana-Champaign (UIUC)](https://healtheng.illinois.edu/AICommunityHealth){target="blank"}
UIUC is hiring 4 tenure-track faculty at all levels in the area of “AI for Community Health” which includes mHealth, Health AI, Public Health, and related topics. This is the first of several investments UIUC will be making to grow computational health research with a focus on the individual and community aspects, and our interests are broad. Interested candidates can reach out to Jim Rehg at [jrehg@illinois.edu](mailto:jrehg@illinois.edu) for further information.

## Student and Post-doctoral Opportunities
<!-- ### [Eric and Wendy Schmidt AI in Science Postdoctoral Fellows at The University of Chicago](https://apply.interfolio.com/131477){target="_blank"}
The AI in Science Postdoctoral Fellow Program at the University of Chicago is seeking scholars who seek to advance and accelerate the adoption of artificial intelligence (AI) in the natural sciences. Applications reviewed starting November 1, 2023. 

### [Data Science Institute Postdoctoral Scholars Program AY2024-25](https://uchicago.infoready4.com/#competitionDetail/1911556){target="_blank"}
The Data Science Institute (DSI) at the University of Chicago invites applications for Postdoctoral Scholars who wish to advance cutting-edge data science approaches, methods, and applications in research. Applications are due by January 9, 2024.

### [Social & Responsible AI Summer Internships, Nokia Bell Labs](https://social-dynamics.net/docs/interns_2024.pdf){target="_blank"}
The program welcomes applications from outstanding PhD students (ideally, final-year PhD students) for summer internships (fully paid), typically between the beginning of June and the end of August. Main internship projects include: 1. Quantifying the Impact of AI on Jobs.  2. A Comparative Study of Constitutional AI approaches. 3. Visualization Tools for Generative AI and Risk Assessment. 4. Beyond Model Cards. Applications due January 17, 2024.

### [Intelligence Community Postdoctoral Research Fellowship Program (IC Postdoc Program)](https://orise.orau.gov/icpostdoc/){target="_blank"}
The IC Postdoc Program offers scientists and engineers from a wide variety of disciplines unique opportunities to conduct research in a wide range of topics relevant to the Intelligence Community. The research is conducted by the Postdocs, in partnership with a Research Advisor while also collaborating with an advisor from the Intelligence Community. A multitude of [opportunities](https://orise.orau.gov/icpostdoc/current-opportunities.html){target="_blank"} are available across many fields relevant to data science, machine learning, and artificial intelligence. Applications are due by February 28, 2024 for appointments starting on September 30, 2024. Information session and recruitment fair on Thursday, January 18, 2024 from 11am-2pm - [register now](https://app.brazenconnect.com/events/ogQKW){target="_blank"}!-->

### [S. Scott Collis Fellowship in Data Science](https://www.sandia.gov/careers/career-possibilities/students-and-postdocs/fellowships/data-science-fellowship/){target="_blank"}
The S. Scott Collis Fellowship in Data Science seeks applicants with a demonstrated background and interest in the interdisciplinary domain of data science to include mathematics, computer science, artificial intelligence, statistics, computer engineering, and related areas. Collis Data Science Fellows work at the junction of cutting-edge data science techniques and Sandia’s national security mission and application space. 

## Seeking a Position, Collaboration, or Project
No active posts.

***

If you are looking to fill a position or seeking a specific collaborator, contact [Penny Atkins](mailto:pennyatkins@hsc.utah.edu?subject=Positions%20and%20Projects%20Post) with a brief statement of either your open position or project or your strengths and interests if seeking a position or project. 
